//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChangeEventEventType.
const (
	ChannelCreated  ChangeEventEventType = "channel.created"
	ChannelDeleted  ChangeEventEventType = "channel.deleted"
	ChannelUpdated  ChangeEventEventType = "channel.updated"
	PostCreated     ChangeEventEventType = "post.created"
	PostDeleted     ChangeEventEventType = "post.deleted"
	PostUpdated     ChangeEventEventType = "post.updated"
	ReactionUpdated ChangeEventEventType = "reaction.updated"
	ReplyCreated    ChangeEventEventType = "reply.created"
	ReplyDeleted    ChangeEventEventType = "reply.deleted"
	ReplyUpdated    ChangeEventEventType = "reply.updated"
)

// Valid indicates whether the value is a known member of the ChangeEventEventType enum.
func (e ChangeEventEventType) Valid() bool {
	switch e {
	case ChannelCreated:
		return true
	case ChannelDeleted:
		return true
	case ChannelUpdated:
		return true
	case PostCreated:
		return true
	case PostDeleted:
		return true
	case PostUpdated:
		return true
	case ReactionUpdated:
		return true
	case ReplyCreated:
		return true
	case ReplyDeleted:
		return true
	case ReplyUpdated:
		return true
	default:
		return false
	}
}

// Defines values for HealthDatabase.
const (
	HealthDatabaseOk          HealthDatabase = "ok"
	HealthDatabaseSkipped     HealthDatabase = "skipped"
	HealthDatabaseUnreachable HealthDatabase = "unreachable"
)

// Valid indicates whether the value is a known member of the HealthDatabase enum.
func (e HealthDatabase) Valid() bool {
	switch e {
	case HealthDatabaseOk:
		return true
	case HealthDatabaseSkipped:
		return true
	case HealthDatabaseUnreachable:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk        HealthStatus = "ok"
	HealthStatusUnhealthy HealthStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	case HealthStatusUnhealthy:
		return true
	default:
		return false
	}
}

// Attachment defines model for Attachment.
type Attachment struct {
	Checksum    string              `json:"checksum"`
	ContentType string              `json:"contentType"`
	CreatedAt   time.Time           `json:"createdAt"`
	FileName    string              `json:"fileName"`
	Id          openapi_types.UUID  `json:"id"`
	PostId      *openapi_types.UUID `json:"postId,omitempty"`
	SizeBytes   int64               `json:"sizeBytes"`
}

// ChangeEvent defines model for ChangeEvent.
type ChangeEvent struct {
	ChannelId *openapi_types.UUID  `json:"channelId,omitempty"`
	CreatedAt time.Time            `json:"createdAt"`
	EventType ChangeEventEventType `json:"eventType"`

	// Id JavaScript で精度を失わない十進文字列の単調増加 ID。
	Id           string              `json:"id"`
	PostId       *openapi_types.UUID `json:"postId,omitempty"`
	ThreadRootId *openapi_types.UUID `json:"threadRootId,omitempty"`
}

// ChangeEventEventType defines model for ChangeEvent.EventType.
type ChangeEventEventType string

// ChangeEventPage defines model for ChangeEventPage.
type ChangeEventPage struct {
	Events    []ChangeEvent `json:"events"`
	HasMore   bool          `json:"hasMore"`
	NextAfter string        `json:"nextAfter"`

	// ResetRequired 指定カーソルが保持期間外で、表示中データの全再取得が必要か。省略時は false
	ResetRequired *bool `json:"resetRequired,omitempty"`
}

// Channel defines model for Channel.
type Channel struct {
	CreatedAt time.Time           `json:"createdAt"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
	ParentId  *openapi_types.UUID `json:"parentId,omitempty"`
	SortKey   string              `json:"sortKey"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// ChannelList defines model for ChannelList.
type ChannelList struct {
	Channels []Channel `json:"channels"`
}

// CreateChannelRequest defines model for CreateChannelRequest.
type CreateChannelRequest struct {
	Name     string              `json:"name"`
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`
}

// CreateEmojiRequest defines model for CreateEmojiRequest.
type CreateEmojiRequest struct {
	// File PNG または GIF の画像。512 KiB 以下。
	File openapi_types.File `json:"file"`

	// Shortcode 使える文字は英数字・`_`・`-`。先頭は英数字で、長さは 1〜64。
	Shortcode string `json:"shortcode"`
}

// CreatePostRequest defines model for CreatePostRequest.
type CreatePostRequest struct {
	AttachmentIds *[]openapi_types.UUID `json:"attachmentIds,omitempty"`

	// Body 本文。添付が無い場合は空であってはならない。
	Body *string `json:"body,omitempty"`
}

// DownloadUrlResponse defines model for DownloadUrlResponse.
type DownloadUrlResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Url       string    `json:"url"`
}

// EditPostRequest defines model for EditPostRequest.
type EditPostRequest struct {
	// AttachmentIds 指定した場合は添付の集合を置き換える。省略時は既存の添付を維持する。
	AttachmentIds *[]openapi_types.UUID `json:"attachmentIds,omitempty"`
	Body          string                `json:"body"`
}

// Emoji defines model for Emoji.
type Emoji struct {
	Checksum  string             `json:"checksum"`
	Id        openapi_types.UUID `json:"id"`
	ImagePath string             `json:"imagePath"`
	Shortcode string             `json:"shortcode"`
}

// EmojiList defines model for EmojiList.
type EmojiList struct {
	Emojis []Emoji `json:"emojis"`
}

// Error defines model for Error.
type Error struct {
	// Code 機械可読なエラーコード
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message 人間可読なメッセージ
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Database HealthDatabase `json:"database"`
	Status   HealthStatus   `json:"status"`
}

// HealthDatabase defines model for Health.Database.
type HealthDatabase string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// MoveChannelRequest defines model for MoveChannelRequest.
type MoveChannelRequest struct {
	// AfterId このチャネルの直後に挿入する。
	AfterId *openapi_types.UUID `json:"afterId,omitempty"`

	// BeforeId このチャネルの直前に挿入する。null なら末尾。
	BeforeId *openapi_types.UUID `json:"beforeId,omitempty"`
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`
}

// Post defines model for Post.
type Post struct {
	Attachments *[]Attachment      `json:"attachments,omitempty"`
	AuthorId    openapi_types.UUID `json:"authorId"`
	Body        string             `json:"body"`
	ChannelId   openapi_types.UUID `json:"channelId"`
	CreatedAt   time.Time          `json:"createdAt"`

	// Deleted 論理削除済み。スレッド親のプレースホルダでのみ true になる。
	Deleted     bool               `json:"deleted"`
	EditedAt    *time.Time         `json:"editedAt,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	LastReplyAt *time.Time         `json:"lastReplyAt,omitempty"`

	// Reactions 最初に付与された順のリアクション集計。
	Reactions    *[]Reaction         `json:"reactions,omitempty"`
	ReplyCount   int                 `json:"replyCount"`
	ThreadRootId *openapi_types.UUID `json:"threadRootId,omitempty"`
	UpdatedAt    time.Time           `json:"updatedAt"`
}

// PostList defines model for PostList.
type PostList struct {
	// NextBefore より古いポストを取得するカーソル。これ以上過去が無ければ null。
	NextBefore *string `json:"nextBefore,omitempty"`
	Posts      []Post  `json:"posts"`
}

// Reaction defines model for Reaction.
type Reaction struct {
	Count       int   `json:"count"`
	Emoji       Emoji `json:"emoji"`
	ReactedByMe bool  `json:"reactedByMe"`

	// ReactorIds 付与者 ID。reactedByMe が true の場合は現在のユーザーを先頭にする。
	ReactorIds []openapi_types.UUID `json:"reactorIds"`
}

// RenameChannelRequest defines model for RenameChannelRequest.
type RenameChannelRequest struct {
	Name string `json:"name"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Body         string              `json:"body"`
	ChannelId    openapi_types.UUID  `json:"channelId"`
	ChannelName  string              `json:"channelName"`
	CreatedAt    time.Time           `json:"createdAt"`
	PostId       openapi_types.UUID  `json:"postId"`
	ThreadRootId *openapi_types.UUID `json:"threadRootId,omitempty"`

	// TimelinePostId チャネルタイムラインに表示するルートポスト ID。
	TimelinePostId openapi_types.UUID `json:"timelinePostId"`
}

// SearchResultPage defines model for SearchResultPage.
type SearchResultPage struct {
	NextCursor *string        `json:"nextCursor,omitempty"`
	Results    []SearchResult `json:"results"`
}

// StartUploadRequest defines model for StartUploadRequest.
type StartUploadRequest struct {
	// Checksum SHA-256 の hex
	Checksum    string `json:"checksum"`
	ContentType string `json:"contentType"`
	FileName    string `json:"fileName"`
	SizeBytes   int64  `json:"sizeBytes"`
}

// StartUploadResponse defines model for StartUploadResponse.
type StartUploadResponse struct {
	Headers   map[string]string  `json:"headers"`
	Id        openapi_types.UUID `json:"id"`
	UploadUrl string             `json:"uploadUrl"`
}

// Thread defines model for Thread.
type Thread struct {
	Replies []Post `json:"replies"`
	Root    Post   `json:"root"`
}

// AttachmentId defines model for AttachmentId.
type AttachmentId = openapi_types.UUID

// ChannelId defines model for ChannelId.
type ChannelId = openapi_types.UUID

// EmojiId defines model for EmojiId.
type EmojiId = openapi_types.UUID

// EmojiShortcode defines model for EmojiShortcode.
type EmojiShortcode = string

// PostId defines model for PostId.
type PostId = openapi_types.UUID

// ListChannelPostsParams defines parameters for ListChannelPosts.
type ListChannelPostsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Before より古いポストを取るカーソル（nextBefore の値）
	Before *string `form:"before,omitempty" json:"before,omitempty"`

	// Around 検索結果から移動するとき、このルートポストを含む履歴を返す。
	Around *openapi_types.UUID `form:"around,omitempty" json:"around,omitempty"`
}

// ListChangeEventsParams defines parameters for ListChangeEvents.
type ListChangeEventsParams struct {
	// After 数値 ID、または履歴を再生せず現在位置から開始する `latest`
	After *string `form:"after,omitempty" json:"after,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// SearchPostsParams defines parameters for SearchPosts.
type SearchPostsParams struct {
	Q           string              `form:"q" json:"q"`
	ChannelId   *openapi_types.UUID `form:"channelId,omitempty" json:"channelId,omitempty"`
	CreatedFrom *time.Time          `form:"createdFrom,omitempty" json:"createdFrom,omitempty"`
	CreatedTo   *time.Time          `form:"createdTo,omitempty" json:"createdTo,omitempty"`
	Limit       *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor      *string             `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// StartAttachmentUploadJSONRequestBody defines body for StartAttachmentUpload for application/json ContentType.
type StartAttachmentUploadJSONRequestBody = StartUploadRequest

// CreateChannelJSONRequestBody defines body for CreateChannel for application/json ContentType.
type CreateChannelJSONRequestBody = CreateChannelRequest

// RenameChannelJSONRequestBody defines body for RenameChannel for application/json ContentType.
type RenameChannelJSONRequestBody = RenameChannelRequest

// MoveChannelJSONRequestBody defines body for MoveChannel for application/json ContentType.
type MoveChannelJSONRequestBody = MoveChannelRequest

// CreateChannelPostJSONRequestBody defines body for CreateChannelPost for application/json ContentType.
type CreateChannelPostJSONRequestBody = CreatePostRequest

// CreateEmojiMultipartRequestBody defines body for CreateEmoji for multipart/form-data ContentType.
type CreateEmojiMultipartRequestBody = CreateEmojiRequest

// EditPostJSONRequestBody defines body for EditPost for application/json ContentType.
type EditPostJSONRequestBody = EditPostRequest

// CreateReplyJSONRequestBody defines body for CreateReply for application/json ContentType.
type CreateReplyJSONRequestBody = CreatePostRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// StartAttachmentUpload 添付のアップロード用署名付き URL を発行する
	// (POST /v1/attachments/uploads)
	StartAttachmentUpload(w http.ResponseWriter, r *http.Request)
	// CompleteAttachment アップロード完了を通知しメタデータを確定する
	// (POST /v1/attachments/{attachmentId}/complete)
	CompleteAttachment(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId)
	// GetAttachmentDownload ダウンロード用の短期署名付き URL を発行する
	// (GET /v1/attachments/{attachmentId}/download)
	GetAttachmentDownload(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId)
	// ListChannels チャネル階層を一覧する
	// (GET /v1/channels)
	ListChannels(w http.ResponseWriter, r *http.Request)
	// CreateChannel チャネルを作成する
	// (POST /v1/channels)
	CreateChannel(w http.ResponseWriter, r *http.Request)
	// DeleteChannel ポストを持たないチャネルを削除する
	// (DELETE /v1/channels/{channelId})
	DeleteChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// RenameChannel チャネルをリネームする
	// (PATCH /v1/channels/{channelId})
	RenameChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// MoveChannel 親の付け替えと並び替え
	// (POST /v1/channels/{channelId}/move)
	MoveChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// ListChannelPosts チャネル直下のポストを keyset で取得する
	// (GET /v1/channels/{channelId}/posts)
	ListChannelPosts(w http.ResponseWriter, r *http.Request, channelId ChannelId, params ListChannelPostsParams)
	// CreateChannelPost チャネル直下にポストを作成する
	// (POST /v1/channels/{channelId}/posts)
	CreateChannelPost(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// ListEmojis 登録済みのカスタム絵文字を一覧する
	// (GET /v1/emojis)
	ListEmojis(w http.ResponseWriter, r *http.Request)
	// CreateEmoji カスタム絵文字を 1 件登録する
	// (POST /v1/emojis)
	CreateEmoji(w http.ResponseWriter, r *http.Request)
	// GetEmojiImage カスタム絵文字の画像を取得する
	// (GET /v1/emojis/{shortcode}/image)
	GetEmojiImage(w http.ResponseWriter, r *http.Request, shortcode EmojiShortcode)
	// ListChangeEvents 指定したイベント ID より後の変更を取得する
	// (GET /v1/events)
	ListChangeEvents(w http.ResponseWriter, r *http.Request, params ListChangeEventsParams)
	// DeletePost ポストを論理削除する
	// (DELETE /v1/posts/{postId})
	DeletePost(w http.ResponseWriter, r *http.Request, postId PostId)
	// EditPost ポスト本文を上書きする
	// (PATCH /v1/posts/{postId})
	EditPost(w http.ResponseWriter, r *http.Request, postId PostId)
	// RemoveReaction 自身のリアクションを解除する
	// (DELETE /v1/posts/{postId}/reactions/{emojiId})
	RemoveReaction(w http.ResponseWriter, r *http.Request, postId PostId, emojiId EmojiId)
	// AddReaction ポストへリアクションを付与する
	// (PUT /v1/posts/{postId}/reactions/{emojiId})
	AddReaction(w http.ResponseWriter, r *http.Request, postId PostId, emojiId EmojiId)
	// CreateReply スレッドへ返信する
	// (POST /v1/posts/{postId}/replies)
	CreateReply(w http.ResponseWriter, r *http.Request, postId PostId)
	// GetThread 親ポストと返信を古い順で取得する
	// (GET /v1/posts/{postId}/thread)
	GetThread(w http.ResponseWriter, r *http.Request, postId PostId)
	// SearchPosts ポスト本文を全文検索する
	// (GET /v1/search)
	SearchPosts(w http.ResponseWriter, r *http.Request, params SearchPostsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartAttachmentUpload operation middleware
func (siw *ServerInterfaceWrapper) StartAttachmentUpload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartAttachmentUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteAttachment operation middleware
func (siw *ServerInterfaceWrapper) CompleteAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId AttachmentId

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", r.PathValue("attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteAttachment(w, r, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAttachmentDownload operation middleware
func (siw *ServerInterfaceWrapper) GetAttachmentDownload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId AttachmentId

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", r.PathValue("attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAttachmentDownload(w, r, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChannels operation middleware
func (siw *ServerInterfaceWrapper) ListChannels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChannel operation middleware
func (siw *ServerInterfaceWrapper) CreateChannel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChannel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameChannel operation middleware
func (siw *ServerInterfaceWrapper) RenameChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MoveChannel operation middleware
func (siw *ServerInterfaceWrapper) MoveChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MoveChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChannelPosts operation middleware
func (siw *ServerInterfaceWrapper) ListChannelPosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChannelPostsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "around" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "around", r.URL.Query(), &params.Around, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "around"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "around", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannelPosts(w, r, channelId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChannelPost operation middleware
func (siw *ServerInterfaceWrapper) CreateChannelPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChannelPost(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEmojis operation middleware
func (siw *ServerInterfaceWrapper) ListEmojis(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEmojis(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEmoji operation middleware
func (siw *ServerInterfaceWrapper) CreateEmoji(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEmoji(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEmojiImage operation middleware
func (siw *ServerInterfaceWrapper) GetEmojiImage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shortcode" -------------
	var shortcode EmojiShortcode

	err = runtime.BindStyledParameterWithOptions("simple", "shortcode", r.PathValue("shortcode"), &shortcode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shortcode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEmojiImage(w, r, shortcode)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChangeEvents operation middleware
func (siw *ServerInterfaceWrapper) ListChangeEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChangeEventsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChangeEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePost operation middleware
func (siw *ServerInterfaceWrapper) DeletePost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePost(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EditPost operation middleware
func (siw *ServerInterfaceWrapper) EditPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EditPost(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveReaction operation middleware
func (siw *ServerInterfaceWrapper) RemoveReaction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	// ------------- Path parameter "emojiId" -------------
	var emojiId EmojiId

	err = runtime.BindStyledParameterWithOptions("simple", "emojiId", r.PathValue("emojiId"), &emojiId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "emojiId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveReaction(w, r, postId, emojiId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddReaction operation middleware
func (siw *ServerInterfaceWrapper) AddReaction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	// ------------- Path parameter "emojiId" -------------
	var emojiId EmojiId

	err = runtime.BindStyledParameterWithOptions("simple", "emojiId", r.PathValue("emojiId"), &emojiId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "emojiId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddReaction(w, r, postId, emojiId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateReply operation middleware
func (siw *ServerInterfaceWrapper) CreateReply(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateReply(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetThread operation middleware
func (siw *ServerInterfaceWrapper) GetThread(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetThread(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchPosts operation middleware
func (siw *ServerInterfaceWrapper) SearchPosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchPostsParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "channelId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channelId", r.URL.Query(), &params.ChannelId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "channelId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "createdFrom" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "createdFrom", r.URL.Query(), &params.CreatedFrom, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "createdFrom"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "createdFrom", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "createdTo" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "createdTo", r.URL.Query(), &params.CreatedTo, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "createdTo"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "createdTo", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/channels", wrapper.ListChannels)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/channels", wrapper.CreateChannel)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/channels/{channelId}", wrapper.DeleteChannel)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/channels/{channelId}", wrapper.RenameChannel)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/channels/{channelId}/move", wrapper.MoveChannel)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/channels/{channelId}/posts", wrapper.ListChannelPosts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/channels/{channelId}/posts", wrapper.CreateChannelPost)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/posts/{postId}", wrapper.DeletePost)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/posts/{postId}", wrapper.EditPost)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/posts/{postId}/thread", wrapper.GetThread)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/posts/{postId}/replies", wrapper.CreateReply)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/attachments/uploads", wrapper.StartAttachmentUpload)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/attachments/{attachmentId}/complete", wrapper.CompleteAttachment)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/attachments/{attachmentId}/download", wrapper.GetAttachmentDownload)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/emojis", wrapper.ListEmojis)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/emojis", wrapper.CreateEmoji)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/emojis/{shortcode}/image", wrapper.GetEmojiImage)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/posts/{postId}/reactions/{emojiId}", wrapper.RemoveReaction)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/posts/{postId}/reactions/{emojiId}", wrapper.AddReaction)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/search", wrapper.SearchPosts)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/events", wrapper.ListChangeEvents)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5HxpUxvXnvdXUfWTF8/UCEs4S9Wlal5gx3G4N7lF2U5N1fgydhsdUMdSt9LdYsJlqNJpBbOJQIgNtsED",
	"JjKWzUXgLSEs5sMctZZX+QpTZ+lVp7WA5JmqeUNJ6tNn+S+//3qYEIaVZEqRgaxrQt+EkBJVMQl0oJJv",
	"/bouDseTQNYHYvi7JAt9QkrU40JYkMUkEPoE0T0kLKjgu7SkgpjQp6tpEBa04ThIivjdEUVNirrQJ6TT",
	"Eh6pj6fw+5quSvKoMDkZFi7HRVkGicClhu3n51vnSlL5VgpcBbCnHVjjelxR9WElBgKW0uznjRZLiboO",
	"VPz2v9/s7/k3sefv0Z4/DTkfb/UMTUTDn308+RF3J4OKFsy9FH14nrNO4pe1lCJrgMjMFVVVVPxhWJF1",
	"IOv4o5hKJaRhUZcUOfKtpsj4N2eFj1QwIvQJ/y/iiGKEPtUidDaySgxow6qUwpMIfULpIFN9vYPgKoIb",
	"yCig7AuUPTZPtszjRXJsNoFXigk5VSUFVF2iux2Og+G7WjqJP/tOFrZOcIP8znuuAlEHsX7dQ6eYqIMe",
	"XUqCemKFhREpAf5KaM+ZT4q1QPCwxTTOUDmdSIh3EsDiYt2rmvR3cGlcp2e335Zk/bNPnJUkWQejQBUo",
	"ay25uCmQJewDeMnjnjrsUNVNoyF7AeXOt2BYF5jKj4IrYwG8ceFB20c9A3PAmIvbQMZScdPaxQU2Hzkd",
	"/SWdivl+iYEEoL9gHrleIV+d8eSrM1gFqcS4azT97gyn393jxWGsBvaQoXCQMHmV5s/imHidfA8h+Lzy",
	"+r15uI2MZTP/ChmLCL5E8AdzAdYyr8sr0+buqjmzimDRXHhYfXlqbq2ac5uhgc9RxsAncIEShqN//qjD",
	"kqrHVSDGrinK2Sbgia7D3jbEclAcBfWiSaYinyQdJLVmKOYW80l7PVFVxXH8PS5qXyuqGxPuKEoCiDJ+",
	"KIPv9f4RHah+WxBMdhVoQL9mH98vBeXctFl8jIwdlD1GxgnK7iCYK50+KedgeX2jtvKzmV9B8DnKwOrT",
	"QiV/WDrYRdlpMvgUy8NUwby3YC6umO9XEcyZp1PVbYjgPMoYlXVYefCs/MhAcC80IiY0l5rZR/KxhpHS",
	"fVCHIkHMkUGCgxfta3yLiCsHIXZKVG3nqH0wVlT9L2CcOzHT7NbPwhN4meK0tY5b6t0rNCDyV5IWDMzt",
	"yT9mWZ3s+3ZtT8zdEtk8mwpLN+DtzWJVUpK/AvKoHhf6esMdZZxvz2TB4P0SRzBwt9ia1ivo4F+vhhB8",
	"jz0buBe6OvBFCMFi5f6RmV1EGePT3ouhv0iXQqWjZ6WDeQrH9hHuSLKojvNkWHM7oz5f6uQUwRlkzFPY",
	"R3CvOv+q/GAff84e3b51G//tuY0yhjk1U9vc9QwgQFF78BuCD/Bue1Fm/bNP6o3EGTxXN5XdrjIhWjDF",
	"scMbSHB3uOKV36YgkBS/H6CDe6P1GH5HiY1zoHb9H+WVaZQxyr8dlY4eIpir/PAUW9nNt+bSDIJ7lReH",
	"mILQQPAXBLcR3MNm2JilxpiSsZ4ydSf/XPkPOaGIsW/UxDXmjHOM1vcpSQVaO/iYVhMcePLxBg8Ku2bn",
	"seZKTNLbYwzXZhF33yaeRdRibe0e/sVYrpwUEVwoL65RefaZpPLqlrmLx7MXjeXKr7vlHETwER0shDsu",
	"D41JR0Zx6YVho81wpUVjJiXFUTCIw0DeJB6YaMHGuBXTmdkVAgSejm9bSPjdumWhdGpmV9ik3K1Y4aqP",
	"0FygLL/YKG/tm4t71Ze7RE9Z3ImMN/hvdpZH7xjQRYkaSzEWk/BUYmLQtZrHyjg7SwJNY86nD64PD7GT",
	"Zu8i+xRls8g4Ihs5aAqljFnW9DyifAnEBJUPL1Vioi7eETVPfKTcxVJwV0qlSGySlnF0Eif2kxeWaLqo",
	"p7W6CdJynKw5znnJbwroDGFnN7wjfK2MNfUVROxtDnA8ZAR/RrCIshBlf0HZBeIhFytrb833OQR3yrlT",
	"c+qZGzTadv3ugBFFBW0tPbtQvzReJ0QNRnl9x9x/f8btnM8bqqM9BvpGCN+6ertSN5y4SUzrcUUdaA32",
	"AgA53DjN0Im0ghW41/G6urNSWbpnzs7VHuXLBzMInqKMgYzfUfYfWKOzs9Xtl0QYVskvx+TRGhaJbIZ4",
	"DUUET0OYLSEEd4gczHtcBlcYCWJS4203FZIWzUtCxFY+lRg/z1pWhoPnCaxnzJknCO6Ujh6WDn7EbqeR",
	"Q3CjtnmP0OolMraQsYeM31D2Ocq+qa3dqxZmfMa9kcxdY2vzJI5kYi4raZquSkqylMQgFq3PnZ07g9Gh",
	"GNCdNLf1hWlDUEDoiKznxEMBqs435Dicv0RgjgNyxgwy5szFPPZxs0+IXGP3zUoqEHhz5ycyBsZFI0di",
	"nrka/NH88chypn8i/N8PYXpSNjfHO0VrA4QInDVzMeiUPBLZ8sRxMvyC1MsTJGD5gi05QkR1QOzS+NcB",
	"CSUyAIsBR7moTlUzUzTR55orhGDOgpqiE74svjfXC0Tvtgm3fiV/l604cedsrnVzZ46knzH1vAf2nI7P",
	"DByvdySJ0Goe4DoQ1eH4NaClE5ylOmWW6OjA0sIZzFZw8rbTydqwgPeQkGTgFKt8gOH2h4xTZORRdhP7",
	"3vjDGwR3aKaSSVuWIEd2xoYWO23dvHDn12mClr7teVHVTXoOsDYTCX6CGaPn5bSq0dikBXuJp2od0jwy",
	"2UzhrMm5J9FFVf8mlVDEWKA2uYNWL1uvf9nfc/HTzzCkhOLge65gN6nBNSyoNS53NUJdHwnaq3o1JVRQ",
	"hiYOxBgrvfNDxYlArHRWatFPS6dYwqjFQN8ZH7b3yTvoDYIF9WfDjgT7eA6rGxZURdFbe9cvxvjFsL2P",
	"+r1jgQHDaVXSx6/jiRhAA1EFan+axsP02xcWcf/8rzcEVmsmVpY8dagd1/UULV5L8ohSL/8fh7CnSmHM",
	"2MJIlp0xp17VMo+xRuBT9CcSoS9v3BgM9Q8OMNde0jEQCNbT/sEBISyMAVWjc0Yv9F6IYkIpKSCLKQkv",
	"cyF64WOaj42TM0XidoA/Cgg1MadIfR6jr3AV6CwF4CvuX4xGO1baZytwavuVwrGZXSgd7OJjfBr9+AMs",
	"WXr/xNx9aE7NIJirLp0g+JRkY39AxrxHMIS+m1hwxFGNpC5SmjCEH0fGeiOu+DZClYV21LBg2EthAgdO",
	"dEuBgfVhAE2/xLyCjpyag9GTXuXAVmWyjtW93dkBAz8OE4gOZEm4u0vzabWVefP5PA2iR0TmQPFWsrdu",
	"d4yEBS2dTIrqOI4ZrURx/QqV+4XKyWtzaYEMWAh9c+2rEDKWK48Oq09z1J8QHIa7cxhcxk+489iTZIc4",
	"kvK3Vt3kn8IZEvG0Xk0OhQPk6DJbwJUo6aLKutMxHLXdOrRz9JTi52ZcPb/MYq50eA8Zy7XM48rGM7xa",
	"9il2Ce0KtbFsbeSczIuxokojmHQoYpVgukl/XpmHxwifQJ+fDdkMMraJfXLUBsFiZWO3vL5xZv0Jn08n",
	"GAfd1Wgum76SNP2yNaiL3HHXzDlcqT3+0XyVr61slU4NBAulg20E39Q2sSyb71+YU1mS0lsgAYwT7ZQO",
	"MtXt5x3goDMl3QgyluncdUxyqvCTgbDjrsV3yWxx6/0f2HDZjQscj+FkvTyzZKcf3QTuKLcwn9hSwXzy",
	"qUJkwg5QJ6nXaRkhLxs/J7+72eih4yf1HitLVs8smXMbHTimk/ojZdgNVvb2Hp+u2URM2wISp9OYWFZR",
	"H47XE8eTKuqSjHPTUS3JePRDyHh57W15ZZ9UvYrdFHCUfUk+H6Ps5hnFPJJUxs7gZvkkgQt2rlJil8SA",
	"U6z83yMENfiicr9AhYAUpAohTVH1W3fBOLb05tIOMjIdlQ5a9iIOxU/lNdKbZNlL+rV96bAz/sxD8B6R",
	"5i9vqYqi35JiJNXNSqtF4sUUEcR+ZfX0PpbOjPE32V2dIFWIVasMmymv7IcSUlLSQ6WjX/84nimvbpnF",
	"x6He6B/HsxjoHk6TUtVz12y0HIypSQ+NfQBYQBmI4BMStbhKIQGlE960QjjYExokBKkDTnJH4Ls0ID1k",
	"7JIAOYzgvhNgc7c3SvpgaBrt02iznFobdSBfBeiP4xmnoERKEJn8H8ezQpi7Y0pPz5brMlx1dcX8euXt",
	"VuXdUvm/1hGcR8Zs5fmROf+A5ZRhAftmmCO0Pu9PMduaYL56Vt5965aWgE2KqpKWY0I7dy2GuogAdiWP",
	"ZweYcBXt41quIxXSB6RjbceuyyFoIGPeqhJ55LejpqOy9rZ0MO/eFzKWQ3fBuAZIh7u7nujCDFarO6/b",
	"0NwzJnnIbnrH7pa6D+wasxxrc7+YcaYrjN9xMz7ATba4zcyD02AWGCxeoUO6qGxOAxw3DUZbFwi+WJ1l",
	"VP8q796xHl2D1MGyu8jYPzdlK4+OarnXrAOFqqvxO5l+07VgULhoNde5gkVfOoJ2LsOiWdwonfxM8H0V",
	"wZ8Iys+hDKTXtlD2CBnvSCr8kHzmUAEbuvx6tXBMDO62mwoIHtBz2CXnv8l0HdumsnXgXoh2WBdCVwe+",
	"QBlYOpirPVpyFod7IdZkjTKG/VLl/hvzpzkzkydxOunThYvsSLBo3psyi79jzJnJ28knsony6haCO+bu",
	"Q1Ipp60NvKORhh7rCHuhT6J/whBWnl82l7bxcTPQ7l+1R5n52fLaW+Z9kH5hjtV3NaI3BKNkOqFLKVHV",
	"I9gO9cREXWwXjzzd7h8YkFgHBCcdxqjFEMkW6Q5kJ/mKEurFrp9bGnnq4sGjyITdSDsZIX20jbKO9AYr",
	"GdUUpMhkkVFpxEvJpjcGrE7hSEoebffVehZY1LFvMTi6eJnutefGeAqQa2mkjt8l5tj3KLzNRgFw1pZ3",
	"4Lvya+cnnbtiDbOT7H4Yxyf3+WIP9s1MnnQ0QPuSiO10mvcWKvc3EFxD8DFtzimdLJCueOzR0nIKPXLo",
	"dkLUgabfDnJP2VUsjtcvRL2XO/4/vYv2n3TCf+Le5jhDaOGOLS5GmwUXQ12Ojt33ATkSPvA5jkosR3kH",
	"R6vGzwhuMoQ28ij7iBZ4z1/Nct2FcE8cwnugERUJ1q2lAyV9zFsKIY5SZIJ2vbSQN7S92/+xpKG7gbZj",
	"Xj5r8mmQGbQus3TJtffflfnAqaAgx96bDOycV89mYlelsJs5V147wNF2E0/eK68Ru2c4MsH+h0NDGb4G",
	"ksoYsJszW5Hj6vNfbDlGGYM6duxHy3lmQa9hsGF2/+O5k2LTL6uHO9wWZ6wJZBd1FHP6qM+uB+HWLJ+l",
	"MmlOBGAu5RB8yJpLt2H5lYFgrja9UM1PW468QZ3bytyv5al5180s/NRPSr+D2x+LBfMx2sFkvdUYzol6",
	"ydks5eD3oHcQ+uABVwqslvgGUhCkO3Zz1tnBkhv8kVxurnp6v3T6FIc4hhHyZ1sxsx+VZ09pkGPmH5eL",
	"79y3IBDcK52s+y5F8kIccu3g/3i+hVK6A96zm/4HFv/aAmTd7gTkJt2ZZNTfgaEXYPmXXgoUEULsgsK/",
	"sI50d9bbO1fR2voeSc/CRoHyVaCz7sUuoghbgZv3cWjekRqKAxcFRgXsC+YR/IGWCjqcHrWxgImDRpqM",
	"AwMf2oPcRh3iu4b/p8jVq3+x5fjD3cfdxr93CpiM9nx/oSpJ/nQNr+40nPOG0rEZG4RcF9ut5nB3TLvW",
	"G9Veuhmq1bXW8zzZlX0CI1QNiu7KTxf8WXOqUF6ZpovU6RrTkaFJX5Opt+/45hCmmQbUMUs/yMV8IYKV",
	"7b8DAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
