//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChangeEventEventType.
const (
	ChannelCreated  ChangeEventEventType = "channel.created"
	ChannelDeleted  ChangeEventEventType = "channel.deleted"
	ChannelUpdated  ChangeEventEventType = "channel.updated"
	PostCreated     ChangeEventEventType = "post.created"
	PostDeleted     ChangeEventEventType = "post.deleted"
	PostUpdated     ChangeEventEventType = "post.updated"
	ReactionUpdated ChangeEventEventType = "reaction.updated"
	ReplyCreated    ChangeEventEventType = "reply.created"
	ReplyDeleted    ChangeEventEventType = "reply.deleted"
	ReplyUpdated    ChangeEventEventType = "reply.updated"
)

// Valid indicates whether the value is a known member of the ChangeEventEventType enum.
func (e ChangeEventEventType) Valid() bool {
	switch e {
	case ChannelCreated:
		return true
	case ChannelDeleted:
		return true
	case ChannelUpdated:
		return true
	case PostCreated:
		return true
	case PostDeleted:
		return true
	case PostUpdated:
		return true
	case ReactionUpdated:
		return true
	case ReplyCreated:
		return true
	case ReplyDeleted:
		return true
	case ReplyUpdated:
		return true
	default:
		return false
	}
}

// Defines values for HealthDatabase.
const (
	HealthDatabaseOk          HealthDatabase = "ok"
	HealthDatabaseSkipped     HealthDatabase = "skipped"
	HealthDatabaseUnreachable HealthDatabase = "unreachable"
)

// Valid indicates whether the value is a known member of the HealthDatabase enum.
func (e HealthDatabase) Valid() bool {
	switch e {
	case HealthDatabaseOk:
		return true
	case HealthDatabaseSkipped:
		return true
	case HealthDatabaseUnreachable:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk        HealthStatus = "ok"
	HealthStatusUnhealthy HealthStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	case HealthStatusUnhealthy:
		return true
	default:
		return false
	}
}

// Attachment defines model for Attachment.
type Attachment struct {
	Checksum    string              `json:"checksum"`
	ContentType string              `json:"contentType"`
	CreatedAt   time.Time           `json:"createdAt"`
	FileName    string              `json:"fileName"`
	Id          openapi_types.UUID  `json:"id"`
	PostId      *openapi_types.UUID `json:"postId,omitempty"`
	SizeBytes   int64               `json:"sizeBytes"`
}

// ChangeEvent defines model for ChangeEvent.
type ChangeEvent struct {
	ChannelId *openapi_types.UUID  `json:"channelId,omitempty"`
	CreatedAt time.Time            `json:"createdAt"`
	EventType ChangeEventEventType `json:"eventType"`

	// Id JavaScript で精度を失わない十進文字列の単調増加 ID。
	Id           string              `json:"id"`
	PostId       *openapi_types.UUID `json:"postId,omitempty"`
	ThreadRootId *openapi_types.UUID `json:"threadRootId,omitempty"`
}

// ChangeEventEventType defines model for ChangeEvent.EventType.
type ChangeEventEventType string

// ChangeEventPage defines model for ChangeEventPage.
type ChangeEventPage struct {
	Events    []ChangeEvent `json:"events"`
	HasMore   bool          `json:"hasMore"`
	NextAfter string        `json:"nextAfter"`

	// ResetRequired 指定カーソルが保持期間外で、表示中データの全再取得が必要か。省略時は false
	ResetRequired *bool `json:"resetRequired,omitempty"`
}

// Channel defines model for Channel.
type Channel struct {
	CreatedAt time.Time           `json:"createdAt"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
	ParentId  *openapi_types.UUID `json:"parentId,omitempty"`
	SortKey   string              `json:"sortKey"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// ChannelList defines model for ChannelList.
type ChannelList struct {
	Channels []Channel `json:"channels"`
}

// CreateChannelRequest defines model for CreateChannelRequest.
type CreateChannelRequest struct {
	Name     string              `json:"name"`
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`
}

// CreatePostRequest defines model for CreatePostRequest.
type CreatePostRequest struct {
	AttachmentIds *[]openapi_types.UUID `json:"attachmentIds,omitempty"`

	// Body 本文。添付が無い場合は空であってはならない。
	Body *string `json:"body,omitempty"`
}

// DownloadUrlResponse defines model for DownloadUrlResponse.
type DownloadUrlResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Url       string    `json:"url"`
}

// EditPostRequest defines model for EditPostRequest.
type EditPostRequest struct {
	// AttachmentIds 指定した場合は添付の集合を置き換える。省略時は既存の添付を維持する。
	AttachmentIds *[]openapi_types.UUID `json:"attachmentIds,omitempty"`
	Body          string                `json:"body"`
}

// Emoji defines model for Emoji.
type Emoji struct {
	Checksum  string             `json:"checksum"`
	Id        openapi_types.UUID `json:"id"`
	ImagePath string             `json:"imagePath"`
	Shortcode string             `json:"shortcode"`
}

// EmojiList defines model for EmojiList.
type EmojiList struct {
	Emojis []Emoji `json:"emojis"`
}

// Error defines model for Error.
type Error struct {
	// Code 機械可読なエラーコード
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message 人間可読なメッセージ
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Database HealthDatabase `json:"database"`
	Status   HealthStatus   `json:"status"`
}

// HealthDatabase defines model for Health.Database.
type HealthDatabase string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// MoveChannelRequest defines model for MoveChannelRequest.
type MoveChannelRequest struct {
	// AfterId このチャネルの直後に挿入する。
	AfterId *openapi_types.UUID `json:"afterId,omitempty"`

	// BeforeId このチャネルの直前に挿入する。null なら末尾。
	BeforeId *openapi_types.UUID `json:"beforeId,omitempty"`
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`
}

// Post defines model for Post.
type Post struct {
	Attachments *[]Attachment      `json:"attachments,omitempty"`
	AuthorId    openapi_types.UUID `json:"authorId"`
	Body        string             `json:"body"`
	ChannelId   openapi_types.UUID `json:"channelId"`
	CreatedAt   time.Time          `json:"createdAt"`

	// Deleted 論理削除済み。スレッド親のプレースホルダでのみ true になる。
	Deleted     bool               `json:"deleted"`
	EditedAt    *time.Time         `json:"editedAt,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	LastReplyAt *time.Time         `json:"lastReplyAt,omitempty"`

	// Reactions 最初に付与された順のリアクション集計。
	Reactions    *[]Reaction         `json:"reactions,omitempty"`
	ReplyCount   int                 `json:"replyCount"`
	ThreadRootId *openapi_types.UUID `json:"threadRootId,omitempty"`
	UpdatedAt    time.Time           `json:"updatedAt"`
}

// PostList defines model for PostList.
type PostList struct {
	// NextBefore より古いポストを取得するカーソル。これ以上過去が無ければ null。
	NextBefore *string `json:"nextBefore,omitempty"`
	Posts      []Post  `json:"posts"`
}

// Reaction defines model for Reaction.
type Reaction struct {
	Count       int   `json:"count"`
	Emoji       Emoji `json:"emoji"`
	ReactedByMe bool  `json:"reactedByMe"`

	// ReactorIds 付与者 ID。reactedByMe が true の場合は現在のユーザーを先頭にする。
	ReactorIds []openapi_types.UUID `json:"reactorIds"`
}

// RenameChannelRequest defines model for RenameChannelRequest.
type RenameChannelRequest struct {
	Name string `json:"name"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Body         string              `json:"body"`
	ChannelId    openapi_types.UUID  `json:"channelId"`
	ChannelName  string              `json:"channelName"`
	CreatedAt    time.Time           `json:"createdAt"`
	PostId       openapi_types.UUID  `json:"postId"`
	ThreadRootId *openapi_types.UUID `json:"threadRootId,omitempty"`

	// TimelinePostId チャネルタイムラインに表示するルートポスト ID。
	TimelinePostId openapi_types.UUID `json:"timelinePostId"`
}

// SearchResultPage defines model for SearchResultPage.
type SearchResultPage struct {
	NextCursor *string        `json:"nextCursor,omitempty"`
	Results    []SearchResult `json:"results"`
}

// StartUploadRequest defines model for StartUploadRequest.
type StartUploadRequest struct {
	// Checksum SHA-256 の hex
	Checksum    string `json:"checksum"`
	ContentType string `json:"contentType"`
	FileName    string `json:"fileName"`
	SizeBytes   int64  `json:"sizeBytes"`
}

// StartUploadResponse defines model for StartUploadResponse.
type StartUploadResponse struct {
	Headers   map[string]string  `json:"headers"`
	Id        openapi_types.UUID `json:"id"`
	UploadUrl string             `json:"uploadUrl"`
}

// Thread defines model for Thread.
type Thread struct {
	Replies []Post `json:"replies"`
	Root    Post   `json:"root"`
}

// AttachmentId defines model for AttachmentId.
type AttachmentId = openapi_types.UUID

// ChannelId defines model for ChannelId.
type ChannelId = openapi_types.UUID

// EmojiId defines model for EmojiId.
type EmojiId = openapi_types.UUID

// EmojiShortcode defines model for EmojiShortcode.
type EmojiShortcode = string

// PostId defines model for PostId.
type PostId = openapi_types.UUID

// ListChannelPostsParams defines parameters for ListChannelPosts.
type ListChannelPostsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Before より古いポストを取るカーソル（nextBefore の値）
	Before *string `form:"before,omitempty" json:"before,omitempty"`

	// Around 検索結果から移動するとき、このルートポストを含む履歴を返す。
	Around *openapi_types.UUID `form:"around,omitempty" json:"around,omitempty"`
}

// ListChangeEventsParams defines parameters for ListChangeEvents.
type ListChangeEventsParams struct {
	// After 数値 ID、または履歴を再生せず現在位置から開始する `latest`
	After *string `form:"after,omitempty" json:"after,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// SearchPostsParams defines parameters for SearchPosts.
type SearchPostsParams struct {
	Q           string              `form:"q" json:"q"`
	ChannelId   *openapi_types.UUID `form:"channelId,omitempty" json:"channelId,omitempty"`
	CreatedFrom *time.Time          `form:"createdFrom,omitempty" json:"createdFrom,omitempty"`
	CreatedTo   *time.Time          `form:"createdTo,omitempty" json:"createdTo,omitempty"`
	Limit       *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor      *string             `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// StartAttachmentUploadJSONRequestBody defines body for StartAttachmentUpload for application/json ContentType.
type StartAttachmentUploadJSONRequestBody = StartUploadRequest

// CreateChannelJSONRequestBody defines body for CreateChannel for application/json ContentType.
type CreateChannelJSONRequestBody = CreateChannelRequest

// RenameChannelJSONRequestBody defines body for RenameChannel for application/json ContentType.
type RenameChannelJSONRequestBody = RenameChannelRequest

// MoveChannelJSONRequestBody defines body for MoveChannel for application/json ContentType.
type MoveChannelJSONRequestBody = MoveChannelRequest

// CreateChannelPostJSONRequestBody defines body for CreateChannelPost for application/json ContentType.
type CreateChannelPostJSONRequestBody = CreatePostRequest

// EditPostJSONRequestBody defines body for EditPost for application/json ContentType.
type EditPostJSONRequestBody = EditPostRequest

// CreateReplyJSONRequestBody defines body for CreateReply for application/json ContentType.
type CreateReplyJSONRequestBody = CreatePostRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// StartAttachmentUpload 添付のアップロード用署名付き URL を発行する
	// (POST /v1/attachments/uploads)
	StartAttachmentUpload(w http.ResponseWriter, r *http.Request)
	// CompleteAttachment アップロード完了を通知しメタデータを確定する
	// (POST /v1/attachments/{attachmentId}/complete)
	CompleteAttachment(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId)
	// GetAttachmentDownload ダウンロード用の短期署名付き URL を発行する
	// (GET /v1/attachments/{attachmentId}/download)
	GetAttachmentDownload(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId)
	// ListChannels チャネル階層を一覧する
	// (GET /v1/channels)
	ListChannels(w http.ResponseWriter, r *http.Request)
	// CreateChannel チャネルを作成する
	// (POST /v1/channels)
	CreateChannel(w http.ResponseWriter, r *http.Request)
	// DeleteChannel ポストを持たないチャネルを削除する
	// (DELETE /v1/channels/{channelId})
	DeleteChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// RenameChannel チャネルをリネームする
	// (PATCH /v1/channels/{channelId})
	RenameChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// MoveChannel 親の付け替えと並び替え
	// (POST /v1/channels/{channelId}/move)
	MoveChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// ListChannelPosts チャネル直下のポストを keyset で取得する
	// (GET /v1/channels/{channelId}/posts)
	ListChannelPosts(w http.ResponseWriter, r *http.Request, channelId ChannelId, params ListChannelPostsParams)
	// CreateChannelPost チャネル直下にポストを作成する
	// (POST /v1/channels/{channelId}/posts)
	CreateChannelPost(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// ListEmojis 登録済みのカスタム絵文字を一覧する
	// (GET /v1/emojis)
	ListEmojis(w http.ResponseWriter, r *http.Request)
	// GetEmojiImage カスタム絵文字の PNG を取得する
	// (GET /v1/emojis/{shortcode}/image)
	GetEmojiImage(w http.ResponseWriter, r *http.Request, shortcode EmojiShortcode)
	// ListChangeEvents 指定したイベント ID より後の変更を取得する
	// (GET /v1/events)
	ListChangeEvents(w http.ResponseWriter, r *http.Request, params ListChangeEventsParams)
	// DeletePost ポストを論理削除する
	// (DELETE /v1/posts/{postId})
	DeletePost(w http.ResponseWriter, r *http.Request, postId PostId)
	// EditPost ポスト本文を上書きする
	// (PATCH /v1/posts/{postId})
	EditPost(w http.ResponseWriter, r *http.Request, postId PostId)
	// RemoveReaction 自身のリアクションを解除する
	// (DELETE /v1/posts/{postId}/reactions/{emojiId})
	RemoveReaction(w http.ResponseWriter, r *http.Request, postId PostId, emojiId EmojiId)
	// AddReaction ポストへリアクションを付与する
	// (PUT /v1/posts/{postId}/reactions/{emojiId})
	AddReaction(w http.ResponseWriter, r *http.Request, postId PostId, emojiId EmojiId)
	// CreateReply スレッドへ返信する
	// (POST /v1/posts/{postId}/replies)
	CreateReply(w http.ResponseWriter, r *http.Request, postId PostId)
	// GetThread 親ポストと返信を古い順で取得する
	// (GET /v1/posts/{postId}/thread)
	GetThread(w http.ResponseWriter, r *http.Request, postId PostId)
	// SearchPosts ポスト本文を全文検索する
	// (GET /v1/search)
	SearchPosts(w http.ResponseWriter, r *http.Request, params SearchPostsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartAttachmentUpload operation middleware
func (siw *ServerInterfaceWrapper) StartAttachmentUpload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartAttachmentUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteAttachment operation middleware
func (siw *ServerInterfaceWrapper) CompleteAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId AttachmentId

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", r.PathValue("attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteAttachment(w, r, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAttachmentDownload operation middleware
func (siw *ServerInterfaceWrapper) GetAttachmentDownload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId AttachmentId

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", r.PathValue("attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAttachmentDownload(w, r, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChannels operation middleware
func (siw *ServerInterfaceWrapper) ListChannels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChannel operation middleware
func (siw *ServerInterfaceWrapper) CreateChannel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChannel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameChannel operation middleware
func (siw *ServerInterfaceWrapper) RenameChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MoveChannel operation middleware
func (siw *ServerInterfaceWrapper) MoveChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MoveChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChannelPosts operation middleware
func (siw *ServerInterfaceWrapper) ListChannelPosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChannelPostsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "around" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "around", r.URL.Query(), &params.Around, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "around"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "around", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannelPosts(w, r, channelId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChannelPost operation middleware
func (siw *ServerInterfaceWrapper) CreateChannelPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChannelPost(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEmojis operation middleware
func (siw *ServerInterfaceWrapper) ListEmojis(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEmojis(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEmojiImage operation middleware
func (siw *ServerInterfaceWrapper) GetEmojiImage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shortcode" -------------
	var shortcode EmojiShortcode

	err = runtime.BindStyledParameterWithOptions("simple", "shortcode", r.PathValue("shortcode"), &shortcode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shortcode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEmojiImage(w, r, shortcode)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChangeEvents operation middleware
func (siw *ServerInterfaceWrapper) ListChangeEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChangeEventsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChangeEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePost operation middleware
func (siw *ServerInterfaceWrapper) DeletePost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePost(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EditPost operation middleware
func (siw *ServerInterfaceWrapper) EditPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EditPost(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveReaction operation middleware
func (siw *ServerInterfaceWrapper) RemoveReaction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	// ------------- Path parameter "emojiId" -------------
	var emojiId EmojiId

	err = runtime.BindStyledParameterWithOptions("simple", "emojiId", r.PathValue("emojiId"), &emojiId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "emojiId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveReaction(w, r, postId, emojiId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddReaction operation middleware
func (siw *ServerInterfaceWrapper) AddReaction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	// ------------- Path parameter "emojiId" -------------
	var emojiId EmojiId

	err = runtime.BindStyledParameterWithOptions("simple", "emojiId", r.PathValue("emojiId"), &emojiId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "emojiId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddReaction(w, r, postId, emojiId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateReply operation middleware
func (siw *ServerInterfaceWrapper) CreateReply(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateReply(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetThread operation middleware
func (siw *ServerInterfaceWrapper) GetThread(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetThread(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchPosts operation middleware
func (siw *ServerInterfaceWrapper) SearchPosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchPostsParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "channelId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channelId", r.URL.Query(), &params.ChannelId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "channelId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "createdFrom" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "createdFrom", r.URL.Query(), &params.CreatedFrom, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "createdFrom"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "createdFrom", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "createdTo" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "createdTo", r.URL.Query(), &params.CreatedTo, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "createdTo"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "createdTo", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/channels", wrapper.ListChannels)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/channels", wrapper.CreateChannel)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/channels/{channelId}", wrapper.DeleteChannel)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/channels/{channelId}", wrapper.RenameChannel)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/channels/{channelId}/move", wrapper.MoveChannel)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/channels/{channelId}/posts", wrapper.ListChannelPosts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/channels/{channelId}/posts", wrapper.CreateChannelPost)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/posts/{postId}", wrapper.DeletePost)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/posts/{postId}", wrapper.EditPost)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/posts/{postId}/thread", wrapper.GetThread)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/posts/{postId}/replies", wrapper.CreateReply)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/attachments/uploads", wrapper.StartAttachmentUpload)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/attachments/{attachmentId}/complete", wrapper.CompleteAttachment)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/attachments/{attachmentId}/download", wrapper.GetAttachmentDownload)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/emojis", wrapper.ListEmojis)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/emojis/{shortcode}/image", wrapper.GetEmojiImage)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/posts/{postId}/reactions/{emojiId}", wrapper.RemoveReaction)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/posts/{postId}/reactions/{emojiId}", wrapper.AddReaction)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/search", wrapper.SearchPosts)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/events", wrapper.ListChangeEvents)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FxbUxvHnv8qqtk87NbKluycpGqp2gfi+CQ+m5yibKe2ar1szhi10cTSjDIzYsNhqVKPghFGBA6xwTZ4",
	"wQQDhoPAjpNDuH6Y1ujy5K+w1ZeZ6Rn16AKSd6v2hZI0Pf/u/l9+/b81Y9KQls5oKlBNQ+obkzKyLqeB",
	"CXTyrd805aFkGqjmjQT+rqhSn5SRzaQUlVQ5DaQ+SeaHRCUdfJtVdJCQ+kw9C6KSMZQEaRm/e0/T07Ip",
	"9UnZrIJHmqMZ/L5h6oo6LI2PR6VrSVlVQSp0qiH3+cXmuZ7WvlFCZwHsaRfmuJXUdHNIS4CQqQz3ebPJ",
	"MrJpAh2//R93+i/9m3zpz/FL/zToffz60uBYPPrxh+MfCFcyoBnh0svQhxfZ6zh+2choqgGIzlzXdU3H",
	"H4Y01QSqiT/KmUxKGZJNRVNj3xiain/zZvhAB/ekPunvYp4qxuhTI0apkVkSwBjSlQwmIvVJ5YNc7c0O",
	"gosIriBrC+VfofyxfbJmH8+SbTMCfi0m7NS1DNBNha52KAmG7hvZNP4c2FnU2cFt8rvouQ5kEyT6TR+f",
	"ErIJLplKGjQyKyrdU1Lgj4T3AnpKog2GRx2hCYaq2VRKvpsCjhQbXjWUP4NPRk26d/dtRTU//p03k6Ka",
	"YBjoEhWtoxd3JDKFuwE/e3jSUY+rPI8G3Qm0u9+AIVNiJj8Mro+EyIbDg463eg7hgBFO2kDFWnHHWcVl",
	"Ro/sjv6SzSQCvyRACtBfsIy4V8hXbzz56g3WQSY1yo2m373h9Ds/Xh7CZuAOGYyGKZPfaP4gj8i3yPcI",
	"gpvVN6f24Qay5u3118iaRXAbwe/tGVjPvaksTNq7i3ZhEcGSPfOktn1mry3aD1cjNz5FOQvvgAMlDEf/",
	"+EGXNdVM6kBO3NS08xEQqa4n3g7UckAeBo2qSUiRT4oJ0kYrFOPVfNydT9Z1eRR/T8rGl5rOY8JdTUsB",
	"WcUPVfCd2X/PBHrwLAhnuw4MYN50tx/Ugkpx0i49Q9YOyh8j6wTldxAsls+eV4qwsrxSX/jRXl9AcBPl",
	"YO3FVnX9sHywi/KTZPAZ1oeJLfvBjD27YJ8uIli0zyZqGxDBaZSzqsuw+vhl5amF4F7knpwyODNztxQQ",
	"DWMlv1GPI2HCUUFKgBedW3ybiKuGIXZG1l3nqHMw1nTzX8CokDCz7Pb3IlJ4leK0Mw+v9fwMTZj8hWKE",
	"A3Nn+o9F1qD7gVW7hIVLIotnpLB2A9HaHFGlFfULoA6bSanvSrSrggusmUwYvl7sfoUulnee/dxsqZJp",
	"+bsbdPCVeCOi3NUSowLDX/5rZWES5azK347KR08QLFa/f4Exf/WtPVdAcK/66hAbPrQQ/AnBDQT38KFg",
	"TdGjgSJ/Izcadv6p9p9qSpMTX+mpm8w1FEDodxlFB0Yn1prVUwJjCcgDD4py1EWiuZ5QzM4EI0RQ4ny6",
	"zHOYWqovPcC/WPPVkxKCM5XZJQQLyAoCZGVxzd7F49mL1nz1191KESL4lA6Wol3Xh+asI6OE/MLRTIfO",
	"c5vQqqTlYTCAgxIREYOPoNpAPD6i8ihzDmno7sRIR4LB9nGO8qkVyjGiwqU4wVOA0YwDAS18tVJZ27dn",
	"92rbu8ROWRSErJ/x3/yUiN8JYMoKhW45kVAwKTk1wM3mwzxvZWlgGMwVCgRih4fYZXBXkX+B8nlkHZGF",
	"HLQ8qJiwHPIipnwO5BTVDz9XErIp35UNn7eu3cdacF/JZIinnFWxr5wkaC5ykg1TNrNGA4GsmiRzjgpe",
	"CqyfUYh6qxFt4UttpOXJJWPf54bAX0PwRwRLKA9R/ieUnyH+Wqm69NY+LSK4Uyme2RMvedDo2BG5C+5p",
	"Ouho6qmZxqnxPBF6YFSWd+z903Mu52JncwPvMdA3Q/j2zZtLJAi8eDlrJjX9RnuwFwLI0eZBbzeCXCeM",
	"bJB1bWehOvfAnnpYf7peOSggeIZyFrJ+Q/m/YovOT9U2tokyLJJfjsmjJawS+RzxGkoInkWwWCII7hA9",
	"mPa5DFxQAxJK82W3VJI2j5eUjE/5TGr0InM58bbIE1jO2YXnCO6Uj56UD35A8DGyigiu1FcfEF5tI2sN",
	"WXvI+hvKb6L8z/WlB7WtQuBwb6ZzN9ncIo0jeYFrWpYmT9KKqqQxiMUbMzkXjqe7FJHwKVzXXpg1hIUn",
	"nsr6djwYYurigxwHl58QmBOAnFVA1kN7dh37uPnnRK+x++aEuATe+Gg5Z2FctIrlo5flg4d1+IP9w5Hj",
	"TP+FyH8/gvlJxdwa7zSjAxAicNbKxaAkRSxy9UngZAQV6YpIkYDjC7blCBHTAYlPRr8MSW+QAVgNBMZF",
	"baqWm6BpJ45WBMGiAzUlL3yZPbWXt4jdbRBp/Ur+ztsThfrqLgGl87jWrZ05kgzF3PNv2Lc7sTBw9NiV",
	"kLbdqPQWkPWh5E1gZFOCqbp1LNHRoYnucxxb4anEbqcOoxJeQ0pRgVc6CQAG7w9ZZ8haR/lV7HvjDz8j",
	"uEPzZkzb8gQ58gUXWtwkausyUtCmCVoGludHVZ71AmBtpRLidCdGz2tZ3aCxSRvnJSbVPqT5dLKVwTnE",
	"hTsxZd38KpPS5ESoNfFBq1+stz7vv3T1o48xpESS4DuhYreoCDUt7zQvvjRD3QALOqvBtGRUWIYmCeQE",
	"KwSLQ8WxUKz0ZmrTT8tmWMKozUDfGx911yna6G2CBY17w44E+3iBUzcq6ZpmtvduUI3xi1F3HY1rxwoD",
	"hrK6Yo7ewoQYQANZB3p/lsbD9NvvHeb+4V9vS6zySU5Z8tTjdtI0M7SUqqj3tEb9/zCCPVUKY9YaRrJ8",
	"wZ54Xc89wxaBd9GfSkU+v317INI/cIO59oqJgUBynvYP3JCi0gjQDUozfvnK5ThmlJYBqpxR8DSX45c/",
	"pCWkJNlTLOkG+MOAcBNLilSLMfpKnwGTpQACpear8XjXCs1sBkGlubp1bOdnyge7eBsfxT98D1OWT5/b",
	"u0/siQKCxdrcCYIvSDb2e2RN+xRD6ruDFUceNkjqImNIg/hxbORKjItvY9RYaH8HC4b9HCZw4EW3FBhY",
	"VwAwzE+YV9CVXQswetxvHPhUGW8Q9ZXerICBn0AIxAbyJNzdpfm0+sK0vTlNg+h7MnOgRDO5S3f7F6KS",
	"kU2nZX0Ux4xOorhxhuqjrerJG3tuhgyYiXx184sIsuarTw9rL4rUn5A8gfM5DKHgx/g89jhZIY6kgo0+",
	"d8S78IbEfI1A44PRED26xibgEiU9NFk+HSMw27VDN0dPOX5hwTXKyy4Vy4cPkDVfzz2rrrzEs+VfYJfQ",
	"rZda885CLii8BCuqNINJjyNOCaaX/BeVeUSCCCj0xcWQzyFrg5xPntkgWKqu7FaWV85tP9GL2QSTIF8b",
	"FYrpC8UwrzmDeigdvoIrkEr92Q/26/X6wlr5zEJwq3ywgeDP9VWsy/bpK3siT1J6MySA8aKd8kGutrHZ",
	"BQl6JOlCkDVPaTcIyasJj4fCDl8Z7tGxJaw+v+eDyy2jCzyGk+VKYc5NP/IM7qq0sJzYVOFyCphCbMwN",
	"UMep1+kcQn4xfkp+58Xo4+PvGj1WlqwuzNkPV7qwTS/1R8qwK6zs7d8+nbOFmnYEJF7fKzlZZXMo2cgc",
	"X6qoRzouTEe1pePx96HjlaW3lYV9UvUq9VLBUX6bfD5G+dVzqnksrY2cw80KaIIQ7LhSYo/UQFCs/L+j",
	"BHX4qvpoiyoBKUhtRQxNN7++D0bxSW/P7SAr11XtoGUv4lD8pbJ0hmDBPS/p1861w834Mw/Bv0Wav/xa",
	"1zTzayVBUt2stFoiXkwJQexX1s4eYe3MWf+u8tUJUoVYdMqwucrCfiSlpBUzUj769d1xobK4ZpeeRa7E",
	"3x1PYaB7MklKVZscNVoOxtykm8Y+ANxCOYjgcxK1cKWQkNKJiKwUDfeEBghDGoCTdKx/mwX6qNeyTjYj",
	"8R3qrnSvxEkfDE2jfRRvlVProA4UqAC9Oy54BSVSgsitvzuekqLCFVN++pbckOFqqCuuL1ffrlV/mav8",
	"9zKC08iaqm4e2dOPWU4ZbmHfDEuE1ueDKWbXEuzXLyu7b3ltCVmkrGtZNSF10vk/2EMEcCt5onOAKVfJ",
	"3a7jOlIlfUw61nbcuhyCFrKmnSqRT3+7enRUl96WD6b5dSFrPnIfjBqA9Fvz9UQOM1it7qJuQ2vPmOQh",
	"e+kd8y1179k1ZjnW1n4xk0xPBL/DCz7ETXakzY4Hr8EsNFi8Tof00Ni8BjhhGoy2LhB8cTrLqP1Vf/mF",
	"XhTAJmWd4XDc2r8wZ6tPj+rFN6wDhZqr9Rshv8pNGBYuOs11fgbHxtzOwPEYaQxslkahF8TIqJZcJ8Ri",
	"GXXYz24XO+8qqkxwVnBvKpAncTZXfXRk52e7kK0SMQ6WIgN//CwSaG8QMbBTPApceXMzIt5diab5EHY/",
	"QuAFBND/8b6dWyc1VIjgKQnT9txjzn4wU320guASgs9oO0D5ZIb04eIzlCZw6ZYjf0rJJjDMP4UdiOwq",
	"gsDPkOL+GzB/T+9i/Bcl+A/Ce3jncGZ4b+ZqvJU7M9hjf5y/DyPQ3hufYj/IOZp3sH9s/Yjgqr0+VVl6",
	"SyrjT2lJ6eL5c677miccwWugPhwJD5ypQzV9xJ98JdAcG6N19jYyFe55+r+WpuBb9rrmV7C2gia5CKd9",
	"vkfORLA7/z0Hn2GuhD/90D0/glFilzPwwfawsnSA/fsWvoNfX2Nul2JsjN1hbqrDN0FaGwFuO1g7elzb",
	"/MnVY5SzKotrCO6wH53jmrnZlsWGuR1XFw7DJ7drhzvCpkpsCWQVDRzzOjfPbwfR9k4+x2Sygojenisi",
	"+IS1s23AymsLwWJ9cqa2PklgbAPzi1wHqT78tTIxzd0FwU+DrAwG0v2JRLgc411MDzqtqAI/m+zNMQ5x",
	"12sXoQ8eCLXAacJtogVhtuO2g5wfLFkEFrCZjW0Ei7WzR+WzFwhuIsuKBPM7WNhPK1NnWNg5aK8/q5R+",
	"4fuuEdwrnywHrmGJ4jzS6Pz/PMKjnO6C88zz/8CRX0eAbLq9R8I0H9OMxq57euVO3Ga/RREhwlqi/5n1",
	"wPJ5Nj+tkrP0PZIQgq4OCRJynwGT9Uv1EEXYDMJI0+N5V7K2HlxsMS5gX3Adwe9pcrLLCRkXC5g6GKSt",
	"MTTwoV2PHWQ+v236fzq47uCrbccffOdoB//eJIQY7TL9va6lxeSaXhZoSvO21jWKTUKuq53mj4Urpn2y",
	"zbK9vQzVGpp5RZ7swj6BEWoGJT7X3AN/1p7YqixM0kkabI3ZyOB4oK3N3+l4ZxDzzAD6iGMf5CqwFMPG",
	"9j8BAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
