//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChangeEventEventType.
const (
	ChannelCreated  ChangeEventEventType = "channel.created"
	ChannelDeleted  ChangeEventEventType = "channel.deleted"
	ChannelUpdated  ChangeEventEventType = "channel.updated"
	PostCreated     ChangeEventEventType = "post.created"
	PostDeleted     ChangeEventEventType = "post.deleted"
	PostUpdated     ChangeEventEventType = "post.updated"
	ReactionUpdated ChangeEventEventType = "reaction.updated"
	ReplyCreated    ChangeEventEventType = "reply.created"
	ReplyDeleted    ChangeEventEventType = "reply.deleted"
	ReplyUpdated    ChangeEventEventType = "reply.updated"
)

// Valid indicates whether the value is a known member of the ChangeEventEventType enum.
func (e ChangeEventEventType) Valid() bool {
	switch e {
	case ChannelCreated:
		return true
	case ChannelDeleted:
		return true
	case ChannelUpdated:
		return true
	case PostCreated:
		return true
	case PostDeleted:
		return true
	case PostUpdated:
		return true
	case ReactionUpdated:
		return true
	case ReplyCreated:
		return true
	case ReplyDeleted:
		return true
	case ReplyUpdated:
		return true
	default:
		return false
	}
}

// Defines values for HealthDatabase.
const (
	HealthDatabaseOk          HealthDatabase = "ok"
	HealthDatabaseSkipped     HealthDatabase = "skipped"
	HealthDatabaseUnreachable HealthDatabase = "unreachable"
)

// Valid indicates whether the value is a known member of the HealthDatabase enum.
func (e HealthDatabase) Valid() bool {
	switch e {
	case HealthDatabaseOk:
		return true
	case HealthDatabaseSkipped:
		return true
	case HealthDatabaseUnreachable:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk        HealthStatus = "ok"
	HealthStatusUnhealthy HealthStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	case HealthStatusUnhealthy:
		return true
	default:
		return false
	}
}

// Attachment defines model for Attachment.
type Attachment struct {
	Checksum    string              `json:"checksum"`
	ContentType string              `json:"contentType"`
	CreatedAt   time.Time           `json:"createdAt"`
	FileName    string              `json:"fileName"`
	Id          openapi_types.UUID  `json:"id"`
	PostId      *openapi_types.UUID `json:"postId,omitempty"`
	SizeBytes   int64               `json:"sizeBytes"`
}

// ChangeEvent defines model for ChangeEvent.
type ChangeEvent struct {
	ChannelId *openapi_types.UUID  `json:"channelId,omitempty"`
	CreatedAt time.Time            `json:"createdAt"`
	EventType ChangeEventEventType `json:"eventType"`

	// Id JavaScript で精度を失わない十進文字列の単調増加 ID。
	Id           string              `json:"id"`
	PostId       *openapi_types.UUID `json:"postId,omitempty"`
	ThreadRootId *openapi_types.UUID `json:"threadRootId,omitempty"`
}

// ChangeEventEventType defines model for ChangeEvent.EventType.
type ChangeEventEventType string

// ChangeEventPage defines model for ChangeEventPage.
type ChangeEventPage struct {
	Events    []ChangeEvent `json:"events"`
	HasMore   bool          `json:"hasMore"`
	NextAfter string        `json:"nextAfter"`
}

// Channel defines model for Channel.
type Channel struct {
	CreatedAt time.Time           `json:"createdAt"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
	ParentId  *openapi_types.UUID `json:"parentId,omitempty"`
	SortKey   string              `json:"sortKey"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// ChannelList defines model for ChannelList.
type ChannelList struct {
	Channels []Channel `json:"channels"`
}

// CreateChannelRequest defines model for CreateChannelRequest.
type CreateChannelRequest struct {
	Name     string              `json:"name"`
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`
}

// CreatePostRequest defines model for CreatePostRequest.
type CreatePostRequest struct {
	AttachmentIds *[]openapi_types.UUID `json:"attachmentIds,omitempty"`

	// Body 本文。添付が無い場合は空であってはならない。
	Body *string `json:"body,omitempty"`
}

// DownloadUrlResponse defines model for DownloadUrlResponse.
type DownloadUrlResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Url       string    `json:"url"`
}

// EditPostRequest defines model for EditPostRequest.
type EditPostRequest struct {
	// AttachmentIds 指定した場合は添付の集合を置き換える。省略時は既存の添付を維持する。
	AttachmentIds *[]openapi_types.UUID `json:"attachmentIds,omitempty"`
	Body          string                `json:"body"`
}

// Emoji defines model for Emoji.
type Emoji struct {
	Checksum  string             `json:"checksum"`
	Id        openapi_types.UUID `json:"id"`
	ImagePath string             `json:"imagePath"`
	Shortcode string             `json:"shortcode"`
}

// EmojiList defines model for EmojiList.
type EmojiList struct {
	Emojis []Emoji `json:"emojis"`
}

// Error defines model for Error.
type Error struct {
	// Code 機械可読なエラーコード
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message 人間可読なメッセージ
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Database HealthDatabase `json:"database"`
	Status   HealthStatus   `json:"status"`
}

// HealthDatabase defines model for Health.Database.
type HealthDatabase string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// MoveChannelRequest defines model for MoveChannelRequest.
type MoveChannelRequest struct {
	// AfterId このチャネルの直後に挿入する。
	AfterId *openapi_types.UUID `json:"afterId,omitempty"`

	// BeforeId このチャネルの直前に挿入する。null なら末尾。
	BeforeId *openapi_types.UUID `json:"beforeId,omitempty"`
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`
}

// Post defines model for Post.
type Post struct {
	Attachments *[]Attachment      `json:"attachments,omitempty"`
	AuthorId    openapi_types.UUID `json:"authorId"`
	Body        string             `json:"body"`
	ChannelId   openapi_types.UUID `json:"channelId"`
	CreatedAt   time.Time          `json:"createdAt"`

	// Deleted 論理削除済み。スレッド親のプレースホルダでのみ true になる。
	Deleted     bool               `json:"deleted"`
	EditedAt    *time.Time         `json:"editedAt,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	LastReplyAt *time.Time         `json:"lastReplyAt,omitempty"`

	// Reactions 最初に付与された順のリアクション集計。
	Reactions    *[]Reaction         `json:"reactions,omitempty"`
	ReplyCount   int                 `json:"replyCount"`
	ThreadRootId *openapi_types.UUID `json:"threadRootId,omitempty"`
	UpdatedAt    time.Time           `json:"updatedAt"`
}

// PostList defines model for PostList.
type PostList struct {
	// NextBefore より古いポストを取得するカーソル。これ以上過去が無ければ null。
	NextBefore *string `json:"nextBefore,omitempty"`
	Posts      []Post  `json:"posts"`
}

// Reaction defines model for Reaction.
type Reaction struct {
	Count       int   `json:"count"`
	Emoji       Emoji `json:"emoji"`
	ReactedByMe bool  `json:"reactedByMe"`

	// ReactorIds 付与者 ID。reactedByMe が true の場合は現在のユーザーを先頭にする。
	ReactorIds []openapi_types.UUID `json:"reactorIds"`
}

// RenameChannelRequest defines model for RenameChannelRequest.
type RenameChannelRequest struct {
	Name string `json:"name"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Body         string              `json:"body"`
	ChannelId    openapi_types.UUID  `json:"channelId"`
	ChannelName  string              `json:"channelName"`
	CreatedAt    time.Time           `json:"createdAt"`
	PostId       openapi_types.UUID  `json:"postId"`
	ThreadRootId *openapi_types.UUID `json:"threadRootId,omitempty"`

	// TimelinePostId チャネルタイムラインに表示するルートポスト ID。
	TimelinePostId openapi_types.UUID `json:"timelinePostId"`
}

// SearchResultPage defines model for SearchResultPage.
type SearchResultPage struct {
	NextCursor *string        `json:"nextCursor,omitempty"`
	Results    []SearchResult `json:"results"`
}

// StartUploadRequest defines model for StartUploadRequest.
type StartUploadRequest struct {
	// Checksum SHA-256 の hex
	Checksum    string `json:"checksum"`
	ContentType string `json:"contentType"`
	FileName    string `json:"fileName"`
	SizeBytes   int64  `json:"sizeBytes"`
}

// StartUploadResponse defines model for StartUploadResponse.
type StartUploadResponse struct {
	Headers   map[string]string  `json:"headers"`
	Id        openapi_types.UUID `json:"id"`
	UploadUrl string             `json:"uploadUrl"`
}

// Thread defines model for Thread.
type Thread struct {
	Replies []Post `json:"replies"`
	Root    Post   `json:"root"`
}

// AttachmentId defines model for AttachmentId.
type AttachmentId = openapi_types.UUID

// ChannelId defines model for ChannelId.
type ChannelId = openapi_types.UUID

// EmojiId defines model for EmojiId.
type EmojiId = openapi_types.UUID

// EmojiShortcode defines model for EmojiShortcode.
type EmojiShortcode = string

// PostId defines model for PostId.
type PostId = openapi_types.UUID

// ListChannelPostsParams defines parameters for ListChannelPosts.
type ListChannelPostsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Before より古いポストを取るカーソル（nextBefore の値）
	Before *string `form:"before,omitempty" json:"before,omitempty"`

	// Around 検索結果から移動するとき、このルートポストを含む履歴を返す。
	Around *openapi_types.UUID `form:"around,omitempty" json:"around,omitempty"`
}

// ListChangeEventsParams defines parameters for ListChangeEvents.
type ListChangeEventsParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// SearchPostsParams defines parameters for SearchPosts.
type SearchPostsParams struct {
	Q           string              `form:"q" json:"q"`
	ChannelId   *openapi_types.UUID `form:"channelId,omitempty" json:"channelId,omitempty"`
	CreatedFrom *time.Time          `form:"createdFrom,omitempty" json:"createdFrom,omitempty"`
	CreatedTo   *time.Time          `form:"createdTo,omitempty" json:"createdTo,omitempty"`
	Limit       *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor      *string             `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// StartAttachmentUploadJSONRequestBody defines body for StartAttachmentUpload for application/json ContentType.
type StartAttachmentUploadJSONRequestBody = StartUploadRequest

// CreateChannelJSONRequestBody defines body for CreateChannel for application/json ContentType.
type CreateChannelJSONRequestBody = CreateChannelRequest

// RenameChannelJSONRequestBody defines body for RenameChannel for application/json ContentType.
type RenameChannelJSONRequestBody = RenameChannelRequest

// MoveChannelJSONRequestBody defines body for MoveChannel for application/json ContentType.
type MoveChannelJSONRequestBody = MoveChannelRequest

// CreateChannelPostJSONRequestBody defines body for CreateChannelPost for application/json ContentType.
type CreateChannelPostJSONRequestBody = CreatePostRequest

// EditPostJSONRequestBody defines body for EditPost for application/json ContentType.
type EditPostJSONRequestBody = EditPostRequest

// CreateReplyJSONRequestBody defines body for CreateReply for application/json ContentType.
type CreateReplyJSONRequestBody = CreatePostRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// StartAttachmentUpload 添付のアップロード用署名付き URL を発行する
	// (POST /v1/attachments/uploads)
	StartAttachmentUpload(w http.ResponseWriter, r *http.Request)
	// CompleteAttachment アップロード完了を通知しメタデータを確定する
	// (POST /v1/attachments/{attachmentId}/complete)
	CompleteAttachment(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId)
	// GetAttachmentDownload ダウンロード用の短期署名付き URL を発行する
	// (GET /v1/attachments/{attachmentId}/download)
	GetAttachmentDownload(w http.ResponseWriter, r *http.Request, attachmentId AttachmentId)
	// ListChannels チャネル階層を一覧する
	// (GET /v1/channels)
	ListChannels(w http.ResponseWriter, r *http.Request)
	// CreateChannel チャネルを作成する
	// (POST /v1/channels)
	CreateChannel(w http.ResponseWriter, r *http.Request)
	// DeleteChannel ポストを持たないチャネルを削除する
	// (DELETE /v1/channels/{channelId})
	DeleteChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// RenameChannel チャネルをリネームする
	// (PATCH /v1/channels/{channelId})
	RenameChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// MoveChannel 親の付け替えと並び替え
	// (POST /v1/channels/{channelId}/move)
	MoveChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// ListChannelPosts チャネル直下のポストを keyset で取得する
	// (GET /v1/channels/{channelId}/posts)
	ListChannelPosts(w http.ResponseWriter, r *http.Request, channelId ChannelId, params ListChannelPostsParams)
	// CreateChannelPost チャネル直下にポストを作成する
	// (POST /v1/channels/{channelId}/posts)
	CreateChannelPost(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// ListEmojis 登録済みのカスタム絵文字を一覧する
	// (GET /v1/emojis)
	ListEmojis(w http.ResponseWriter, r *http.Request)
	// GetEmojiImage カスタム絵文字の PNG を取得する
	// (GET /v1/emojis/{shortcode}/image)
	GetEmojiImage(w http.ResponseWriter, r *http.Request, shortcode EmojiShortcode)
	// ListChangeEvents 指定したイベント ID より後の変更を取得する
	// (GET /v1/events)
	ListChangeEvents(w http.ResponseWriter, r *http.Request, params ListChangeEventsParams)
	// DeletePost ポストを論理削除する
	// (DELETE /v1/posts/{postId})
	DeletePost(w http.ResponseWriter, r *http.Request, postId PostId)
	// EditPost ポスト本文を上書きする
	// (PATCH /v1/posts/{postId})
	EditPost(w http.ResponseWriter, r *http.Request, postId PostId)
	// RemoveReaction 自身のリアクションを解除する
	// (DELETE /v1/posts/{postId}/reactions/{emojiId})
	RemoveReaction(w http.ResponseWriter, r *http.Request, postId PostId, emojiId EmojiId)
	// AddReaction ポストへリアクションを付与する
	// (PUT /v1/posts/{postId}/reactions/{emojiId})
	AddReaction(w http.ResponseWriter, r *http.Request, postId PostId, emojiId EmojiId)
	// CreateReply スレッドへ返信する
	// (POST /v1/posts/{postId}/replies)
	CreateReply(w http.ResponseWriter, r *http.Request, postId PostId)
	// GetThread 親ポストと返信を古い順で取得する
	// (GET /v1/posts/{postId}/thread)
	GetThread(w http.ResponseWriter, r *http.Request, postId PostId)
	// SearchPosts ポスト本文を全文検索する
	// (GET /v1/search)
	SearchPosts(w http.ResponseWriter, r *http.Request, params SearchPostsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartAttachmentUpload operation middleware
func (siw *ServerInterfaceWrapper) StartAttachmentUpload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartAttachmentUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteAttachment operation middleware
func (siw *ServerInterfaceWrapper) CompleteAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId AttachmentId

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", r.PathValue("attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteAttachment(w, r, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAttachmentDownload operation middleware
func (siw *ServerInterfaceWrapper) GetAttachmentDownload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "attachmentId" -------------
	var attachmentId AttachmentId

	err = runtime.BindStyledParameterWithOptions("simple", "attachmentId", r.PathValue("attachmentId"), &attachmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attachmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAttachmentDownload(w, r, attachmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChannels operation middleware
func (siw *ServerInterfaceWrapper) ListChannels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChannel operation middleware
func (siw *ServerInterfaceWrapper) CreateChannel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChannel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameChannel operation middleware
func (siw *ServerInterfaceWrapper) RenameChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MoveChannel operation middleware
func (siw *ServerInterfaceWrapper) MoveChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MoveChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChannelPosts operation middleware
func (siw *ServerInterfaceWrapper) ListChannelPosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChannelPostsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "around" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "around", r.URL.Query(), &params.Around, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "around"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "around", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannelPosts(w, r, channelId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChannelPost operation middleware
func (siw *ServerInterfaceWrapper) CreateChannelPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", r.PathValue("channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChannelPost(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEmojis operation middleware
func (siw *ServerInterfaceWrapper) ListEmojis(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEmojis(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEmojiImage operation middleware
func (siw *ServerInterfaceWrapper) GetEmojiImage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shortcode" -------------
	var shortcode EmojiShortcode

	err = runtime.BindStyledParameterWithOptions("simple", "shortcode", r.PathValue("shortcode"), &shortcode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shortcode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEmojiImage(w, r, shortcode)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChangeEvents operation middleware
func (siw *ServerInterfaceWrapper) ListChangeEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChangeEventsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChangeEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePost operation middleware
func (siw *ServerInterfaceWrapper) DeletePost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePost(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EditPost operation middleware
func (siw *ServerInterfaceWrapper) EditPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EditPost(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveReaction operation middleware
func (siw *ServerInterfaceWrapper) RemoveReaction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	// ------------- Path parameter "emojiId" -------------
	var emojiId EmojiId

	err = runtime.BindStyledParameterWithOptions("simple", "emojiId", r.PathValue("emojiId"), &emojiId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "emojiId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveReaction(w, r, postId, emojiId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddReaction operation middleware
func (siw *ServerInterfaceWrapper) AddReaction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	// ------------- Path parameter "emojiId" -------------
	var emojiId EmojiId

	err = runtime.BindStyledParameterWithOptions("simple", "emojiId", r.PathValue("emojiId"), &emojiId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "emojiId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddReaction(w, r, postId, emojiId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateReply operation middleware
func (siw *ServerInterfaceWrapper) CreateReply(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateReply(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetThread operation middleware
func (siw *ServerInterfaceWrapper) GetThread(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "postId" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "postId", r.PathValue("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "postId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetThread(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchPosts operation middleware
func (siw *ServerInterfaceWrapper) SearchPosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchPostsParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "channelId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channelId", r.URL.Query(), &params.ChannelId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "channelId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "createdFrom" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "createdFrom", r.URL.Query(), &params.CreatedFrom, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "createdFrom"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "createdFrom", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "createdTo" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "createdTo", r.URL.Query(), &params.CreatedTo, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "createdTo"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "createdTo", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/channels", wrapper.ListChannels)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/channels", wrapper.CreateChannel)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/channels/{channelId}", wrapper.DeleteChannel)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/channels/{channelId}", wrapper.RenameChannel)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/channels/{channelId}/move", wrapper.MoveChannel)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/channels/{channelId}/posts", wrapper.ListChannelPosts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/channels/{channelId}/posts", wrapper.CreateChannelPost)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/posts/{postId}", wrapper.DeletePost)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/posts/{postId}", wrapper.EditPost)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/posts/{postId}/thread", wrapper.GetThread)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/posts/{postId}/replies", wrapper.CreateReply)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/attachments/uploads", wrapper.StartAttachmentUpload)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/attachments/{attachmentId}/complete", wrapper.CompleteAttachment)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/attachments/{attachmentId}/download", wrapper.GetAttachmentDownload)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/emojis", wrapper.ListEmojis)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/emojis/{shortcode}/image", wrapper.GetEmojiImage)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/posts/{postId}/reactions/{emojiId}", wrapper.RemoveReaction)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/posts/{postId}/reactions/{emojiId}", wrapper.AddReaction)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/search", wrapper.SearchPosts)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/events", wrapper.ListChangeEvents)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FxrU9tWn/8qHm3frRObpO3MMrMvyKUt3bTDJOnszGbZjIJPsBpbciSZDWWYseQQTDCB0gSSQB4IJUBw",
	"ce4pBRI+zLF8eZWv8My5SDqSj3wBO88z87xhLOnof875X37nfxNjwpCSTCkykHVN6B0TUqIqJoEOVHzV",
	"p+viUDwJZL0/hq4lWegVUqIeF8KCLCaB0CuI7JCwoIKbaUkFMaFXV9MgLGhDcZAU0bvXFTUp6kKvkE5L",
	"aKQ+mkLva7oqycPC+HhYOBsXZRkkAqcacp4fb57zSeVnKXAWQJ92YI5LcUXVh5QYCJhKc543miwl6jpQ",
	"0dv/d6XvxP+IJ36JnviPQffn1RODY9Hw16fHv+CuZEDRgqWXIg+Ps9dx9LKWUmQNYJ05r6qKin4MKbIO",
	"ZB39FFOphDQk6pIiR37WFBndc2f4QgXXhV7h3yKuKkbIUy1CqOFZYkAbUqUUIiL0CqXdTPV1ARqL0FiB",
	"5hbMPofZA+vDmnUwi7dNCXi1GLNTVVJA1SWy2qE4GLqhpZPot29nYXsHl/F93nMViDqI9ekePsVEHZzQ",
	"pSSoZ1ZYuC4lwI+Y9xx6UqwFhodtoXGGyulEQryWALYU617VpF/AmVGd7N15W5L1r790Z5JkHQwDVSCi",
	"tfXiioCncDbgZQ9LOuxyleXRoDOBcu1nMKQL1OSHwfmRANkweND2Vo8gHDDCSBvISCuu2Ks4Senh3ZE7",
	"6VTMdycGEoDcQTJiXsGX7nh86Q5WQSoxyowm1+5wcs2OF4eQGThDBsNByuQ1mu/FEfESvg5BY7Py+qO1",
	"twHNeWv9FTRnobENjdvWjFHLvC4vTFo7i1ZuERpFa+ZhdfvQWlu07q6G+s/BjIl2wIASgqN//6LDmqrH",
	"VSDGLirK0QjwVNcVbxtqOSAOg3rVxKTwL0kHSa0ZirFqPu7MJ6qqOIqu46L2g6KymHBNURJAlNFDGdzS",
	"+67rQPWfBUFs922dLpUl5M4YtHkZJDj22L5FtYhochAipkTVcT7aBztF1f8LjHIJU8tpfS88hZIJDtrz",
	"sFrFztCAyRckLRj42tMvJLI63fKt2iHMXRJePCV1EdxMA97abFElJfkCkIf1uNDbE+6o4HxrxhMGrxe5",
	"N4GLZZ1TLzebqmRSvNVPBvdE6y32mhIbrYfX8vIf5YVJmDHLf+6X9h9CI1+5/RRh6upbay4HjReV53vQ",
	"2ISGCY3fobEBjRcIdM0pAr0EWeu5Ubfzc8r/ywlFjP2kJi5S14sDUbdSkgq0dqw1rSY4xuKTBxoUZqjz",
	"RHM+JuntCcbHyPykVXxMnDuHeTZTi7WlO+iOOV/5UITGTHl2CRo5aE7DjFlZNioPnpUfmWj84pq1g8bT",
	"F835yvudct6AxiMyWAh3XB8asw6P4vILRQttOqctQquUFIfBAHL6eUQ0NkJpAfHYiMWlzDh8gbvjIx0O",
	"tlrHOcKnZihHiXKXYgcnPkZTDvi08PlKee2lNfuiur2D7ZRGGdB8g/5mp3j8jgFdlAh0i7GYhEiJiQFm",
	"Ng/muStLAk2jroYv0Nnbqy385q4i+xRms9DcxwvZbXpQUWHZ5HlM+Q6ICaIfXq7ERF28Jmoeb1i5gbTg",
	"hpRKYU80LSNfNI7RnOeEarqop7U6Amk5jucc5bzkWz+lEHZXw9vCD8pI05NLRL5PP8crhsZv0CjCrAGz",
	"v8PsDMwWoFGsLL21PuahUSjnD62JZyxotO2IXAPXFRW0NfXUTP3UaJ4QOTDKywXr5ccjLud4Z3Md7xHQ",
	"N0L41s2bCdQ5XrKY1uOK2t8a7AUAcrhxUNmJINIO0+pkXS0sVObuWFN3a4/Wy7s5aBzCjAnNv2D2D2TR",
	"2anqxjZWhkV85wA/WkIqkc1gr6EIjcMQEksIGgWsB9Mel4EJGkBMarzspkrS4vGSENEpn0qMHmcuO57l",
	"eQLLGSv3BBqF0v7D0u49aDyAZh4aK7XVO5hX29Bcg+YLaP4Js5sw+6a2dKe6lfMd7o107iKdm6dxOO4+",
	"q6RJciIpyVISgVi0PlNy7Hi1QxEJmyJ17IVaQ1B44qqsZ8eDAabOP8hRcHkGwxwH5MwcNO9as+vIx80+",
	"wXqN3DdrdsH6uEjhzSxglf+A9D1jIlw086X9Z6XduzXjnnVv33amf8XyfxlC/CRibo53itYGCGE4a+Zi",
	"EJI8Fjn6xHEy/IrUw1MkYPuCLTlC2HRA7MzoDwHpAzwAqQHHuIhNVTMTJK3D0ApBI29DTdENX2Y/Wstb",
	"2O42sLTe47/z1kSutrqDQekornVzZw4nGxH3vBv27I4vDBQ9diSkbTUqvQREdSh+EWjpBGeqTh1LZHRg",
	"IvkIx1Zwqq7TqbmwgNaQkGTgliZ8gMH6Q+YhNNdhdhX53ujHG2gUqk+3Kut7VNuyGDmyOQdanCRl8zKN",
	"36YxWvqW50VVlvUcYG2mEvx0IkLPs2lVI7FJC+clItU6pHl0spnB2cS5O9FFVf8plVDEWKA1sUGrV6yX",
	"vus7ceqrrxGkhOLgFlexm1RcGpZPGhc3GqGujwXt1TiaMiooQxMHYowWWvmh4lggVrozteinpVM0YdRi",
	"oO+ODzvr5G30MsaC+r0hR4L+PMapGxZURdFbe9evxujFsLOO+rUjhQFDaVXSRy8hQhSggagCtS9N4mFy",
	"9Y3N3O//+7JAK4v4lMVPXW7HdT1FSpWSfF2p1//TIeSpEhgz1xCSZXPWxKta5jGyCLSLvkQi9N3lywOh",
	"voF+6tpLOgICwX7aN9AvhIURoGqEZvRkz8koYpSSArKYktA0J6MnT5MSTRzvKRJ3AvxhgLmJJIWrsQh9",
	"hW+BTlMAvlLuqWi0Y4VcOgOnklvZOrCyM6XdHbSNr6KnP8OUpY9PrJ2H1kQOGvnq3AdoPMXZ2NvQnPYo",
	"htB7BSmOOKzh1EVKEwbR48hIT4SJbyPEWEj/BA2GvRzGcOBGtwQYaNUdaPoZ6hV0ZNccjB73Ggc6Vcbr",
	"RN3TnRVQ8OMIAdtAFoe7OySfVluYtjanSRB9XaQOFG8mZ+lOf0BY0NLJpKiOopjRThTXz1C5v1X58Nqa",
	"m8EDZkI/XbwQguZ85dFe9Wme+BOCK3A2h8EV/Bibxx7HK0SRlL+R5gp/F+6QiKfRZnwwHKBHZ+kETKKk",
	"iybLpmM4Zru25+ToCcePLbh6eVnFfGnvDjTna5nHlZVnaLbsU+QSZidx6HGIhEcXckzhxWhRpRFMuhyx",
	"SzDd5D+vzMMThE+hjy+GbAaaG/h8cs0GGsXKyk55eeXI9hM+nk1QCbK1Ua6YLkiaftYe1EXpsBVcjlRq",
	"j+9Zr9ZrC2ulQxMaW6XdDWi8qa0iXbY+PrcmsjilN4MDGDfaKe1mqhubHZCgS5IsBJrzhHadkNya8Hgg",
	"7LCV4S4dW9zq82c+uJwyOsdj+LBczs056UeWwR2VFpITnSpYTj5TiIw5Aeo48TrtQ8grxnP4PitGDx+/",
	"rPdYabI6N2fdXenANt3UHy7DrtCyt3f7ZM4matoWkLh9pfhkFfWheD1zPKmiLuk4Nx3Vko5HP4eOl5fe",
	"lhde4qpXsZsKDrPb+PcBzK4eUc0jSWXkCG6WTxO4YMeUErukBpxi5T+PEtSM55X7W0QJcEFqK6Qpqn71",
	"BhhFJ701V4BmpqPaQcpe2KH4tbx0CI2cc16Sy/a1w8n4Uw/Bu0WSv7yqKop+VYrhVDctrRaxF1OEBvIr",
	"q4f3kXZmzP+V2eoErkIs2mXYTHnhZSghJSU9VNp//+kgV15cs4qPQz3RTwdTCOgeTuJS1SZDjZSDETfJ",
	"ppEPYGzBjAGNJzhqYUohAaUTHlkhHOwJDWCG1AEn7gi/mQbqqNsSjjcjsB3gjnR7orgPhqTRvoo2y6m1",
	"UQfyVYA+HeTcghIuQWTWPx1MCWHuigk/PUuuy3DV1RXXlytv1yrv5sp/W4bGNDSnKpv71vQDmlM2tpBv",
	"hiRC6vP+FLNjCdarZ+Wdt6y2BCxSVJW0HBPa6awf7CICOJU83jlAlavobNd2HYmSPsAdawWnLgcNE5rT",
	"dpXIo78dPToqS29Lu9PsuqA5H7oBRjWA+5nZeiKDGbRWd1y3oblnjPOQ3fSO2Za6z+wa0xxrc7+YSqYr",
	"gi+wgg9wk21p0+PBbTALDBbPkyFdNDa3AY6bBiOtCxhf7M4yYn+Vd+9IIz4yKfMQhePmy2NztvJov5Z/",
	"TTtQiLmaf2Hyq8yEQeGi3VznZXBkzOkMHI/gxsBGaRTyARYe1ZTrmFgkJQ972e1g5zVJFjHOcr5L8uVJ",
	"7M1V7u9b2dkOZKt4jDOKoYEfvw352ht4DGwXj3yflDkZEfdbhIb5EPr9QYtegEg/FOB4AUK0xe8/0Knb",
	"tofBuhinos18jMEuO8nsRyAcleo/h5wT+7wsIKfV/A0aq9b6VHnpLS5XPyJ1nuMntZmWaJZwCK2BOFbY",
	"Z7enDlS/EW9GFONlZIwUv1tIHziH3D8sd8D20XXssKe1/gYJArunvUsnvL9l/jNHhEHnuzcn0LnDnVKi",
	"X0yg0+ZueWkXOd1NDnSvvkac1sHIGP1wt6EOXwRJZQQ4PVqt6HF183dHj2HGLC+uQaNAb9pnKPV9TZMO",
	"c9qgjh0bT25X9wrcTkdkCXgVdRxz2ymPbgfh1o4j22TSnDDbmstD4yHtMdswyq9MaORrkzPV9UkMYxuI",
	"X/gbjcrd9+WJaeYDDfTUz0p/dNsXiwXLMdrBnJ3dH8pxfvHebOPgt6J2EPqMXa4W2J2xDbQgyHacHo2j",
	"gyUNi3w2s7ENjXz18H7p8Ck0NqFphvxJFyTsR+WpQyTsjGGtPy4X37HN0NB4Ufqw7Ps2ihd84e7jf/Gw",
	"i3C6Ax4ty/9dW35tAbLuNARxc29UM+pb4cl3cPze9y2CCCHap/yftDGVTX55aRXtpb/AWRrD0SFOluxb",
	"oNMmpi6iCJ2BG/65PO9IKtWFiy3KBeQLrkPjNskYdjhL4mABVQcN9xoGRiOkFbGNdOTNhv+cgmnZPdVy",
	"/MG2c7bxPz0CiJHWz29UJckn17CDvyHNy0rHKDYIuU61m9Tlrpg0rzZKwXYzVKvrsOV5sgsvMYwQMyiy",
	"CeAu+LPWxFZ5YZJMUmdr1EYGx329Zt72wyuDiGcaUEds+8Df5woRZGx/DwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
