// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bindAttachment = `-- name: BindAttachment :execrows
update attachments
set post_id = $1
where id = $2
  and uploader_id = $3
  and completed_at is not null
  and post_id is null
  and deletion_pending_at is null
`

type BindAttachmentParams struct {
	PostID     *uuid.UUID
	ID         uuid.UUID
	UploaderID uuid.UUID
}

func (q *Queries) BindAttachment(ctx context.Context, arg BindAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindAttachment, arg.PostID, arg.ID, arg.UploaderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeAttachment = `-- name: CompleteAttachment :one
update attachments
set completed_at = now()
where id = $1
  and uploader_id = $2
  and completed_at is null
  and deletion_pending_at is null
returning id, post_id, uploader_id, file_name, content_type, size_bytes, storage_key, checksum, created_at, completed_at, deletion_pending_at, deletion_attempts, deletion_error
`

type CompleteAttachmentParams struct {
	ID         uuid.UUID
	UploaderID uuid.UUID
}

func (q *Queries) CompleteAttachment(ctx context.Context, arg CompleteAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, completeAttachment, arg.ID, arg.UploaderID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UploaderID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Checksum,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.DeletionPendingAt,
		&i.DeletionAttempts,
		&i.DeletionError,
	)
	return i, err
}

const deleteAttachmentRow = `-- name: DeleteAttachmentRow :exec
delete from attachments
where id = $1
  and deletion_pending_at is not null
`

func (q *Queries) DeleteAttachmentRow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachmentRow, id)
	return err
}

const getAttachment = `-- name: GetAttachment :one
select id, post_id, uploader_id, file_name, content_type, size_bytes, storage_key, checksum, created_at, completed_at, deletion_pending_at, deletion_attempts, deletion_error from attachments
where id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UploaderID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Checksum,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.DeletionPendingAt,
		&i.DeletionAttempts,
		&i.DeletionError,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
insert into attachments (
    id, uploader_id, file_name, content_type, size_bytes, storage_key, checksum
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
returning id, post_id, uploader_id, file_name, content_type, size_bytes, storage_key, checksum, created_at, completed_at, deletion_pending_at, deletion_attempts, deletion_error
`

type InsertAttachmentParams struct {
	ID          uuid.UUID
	UploaderID  uuid.UUID
	FileName    string
	ContentType string
	SizeBytes   int64
	StorageKey  string
	Checksum    string
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.ID,
		arg.UploaderID,
		arg.FileName,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.Checksum,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UploaderID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Checksum,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.DeletionPendingAt,
		&i.DeletionAttempts,
		&i.DeletionError,
	)
	return i, err
}

const listAttachmentsByPostID = `-- name: ListAttachmentsByPostID :many
select id, post_id, uploader_id, file_name, content_type, size_bytes, storage_key, checksum, created_at, completed_at, deletion_pending_at, deletion_attempts, deletion_error from attachments
where post_id = $1
  and completed_at is not null
  and deletion_pending_at is null
order by created_at asc, id asc
`

func (q *Queries) ListAttachmentsByPostID(ctx context.Context, postID *uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UploaderID,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.Checksum,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.DeletionPendingAt,
			&i.DeletionAttempts,
			&i.DeletionError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAttachments = `-- name: ListPendingAttachments :many
select id, post_id, uploader_id, file_name, content_type, size_bytes, storage_key, checksum, created_at, completed_at, deletion_pending_at, deletion_attempts, deletion_error from attachments
where deletion_pending_at is not null
order by deletion_pending_at asc, id asc
limit $1
`

func (q *Queries) ListPendingAttachments(ctx context.Context, rowLimit int32) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listPendingAttachments, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UploaderID,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.Checksum,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.DeletionPendingAt,
			&i.DeletionAttempts,
			&i.DeletionError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReapableAttachmentsPending = `-- name: MarkReapableAttachmentsPending :exec
update attachments a
set post_id = null,
    deletion_pending_at = now(),
    deletion_error = null
where a.deletion_pending_at is null
  and (
    (a.post_id is null and a.created_at < $1)
    or exists (
      select 1 from posts p
      where p.id = a.post_id and p.deleted_at is not null
    )
  )
`

func (q *Queries) MarkReapableAttachmentsPending(ctx context.Context, olderThan time.Time) error {
	_, err := q.db.Exec(ctx, markReapableAttachmentsPending, olderThan)
	return err
}

const recordAttachmentDeletionFailure = `-- name: RecordAttachmentDeletionFailure :exec
update attachments
set deletion_attempts = deletion_attempts + 1,
    deletion_error = left($1, 2000)
where id = $2
  and deletion_pending_at is not null
`

type RecordAttachmentDeletionFailureParams struct {
	DeletionError string
	ID            uuid.UUID
}

func (q *Queries) RecordAttachmentDeletionFailure(ctx context.Context, arg RecordAttachmentDeletionFailureParams) error {
	_, err := q.db.Exec(ctx, recordAttachmentDeletionFailure, arg.DeletionError, arg.ID)
	return err
}

const unbindByPostID = `-- name: UnbindByPostID :exec
update attachments
set post_id = null
where post_id = $1
`

func (q *Queries) UnbindByPostID(ctx context.Context, postID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, unbindByPostID, postID)
	return err
}
