// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bindAttachment = `-- name: BindAttachment :execrows
update attachments
set post_id = $1
where id = $2
  and uploader_id = $3
  and completed_at is not null
  and post_id is null
`

type BindAttachmentParams struct {
	PostID     *uuid.UUID
	ID         uuid.UUID
	UploaderID uuid.UUID
}

func (q *Queries) BindAttachment(ctx context.Context, arg BindAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindAttachment, arg.PostID, arg.ID, arg.UploaderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeAttachment = `-- name: CompleteAttachment :one
update attachments
set completed_at = now()
where id = $1
  and uploader_id = $2
  and completed_at is null
returning id, post_id, uploader_id, file_name, content_type, size_bytes, storage_key, checksum, created_at, completed_at
`

type CompleteAttachmentParams struct {
	ID         uuid.UUID
	UploaderID uuid.UUID
}

func (q *Queries) CompleteAttachment(ctx context.Context, arg CompleteAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, completeAttachment, arg.ID, arg.UploaderID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UploaderID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Checksum,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countStorageKeyRefs = `-- name: CountStorageKeyRefs :one
select count(*)::bigint
from attachments
where storage_key = $1
`

func (q *Queries) CountStorageKeyRefs(ctx context.Context, storageKey string) (int64, error) {
	row := q.db.QueryRow(ctx, countStorageKeyRefs, storageKey)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAttachmentRow = `-- name: DeleteAttachmentRow :exec
delete from attachments
where id = $1
`

func (q *Queries) DeleteAttachmentRow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachmentRow, id)
	return err
}

const getAttachment = `-- name: GetAttachment :one
select id, post_id, uploader_id, file_name, content_type, size_bytes, storage_key, checksum, created_at, completed_at from attachments
where id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UploaderID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Checksum,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
insert into attachments (
    id, uploader_id, file_name, content_type, size_bytes, storage_key, checksum
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
returning id, post_id, uploader_id, file_name, content_type, size_bytes, storage_key, checksum, created_at, completed_at
`

type InsertAttachmentParams struct {
	ID          uuid.UUID
	UploaderID  uuid.UUID
	FileName    string
	ContentType string
	SizeBytes   int64
	StorageKey  string
	Checksum    string
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.ID,
		arg.UploaderID,
		arg.FileName,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.Checksum,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UploaderID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Checksum,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAttachmentsByPostID = `-- name: ListAttachmentsByPostID :many
select id, post_id, uploader_id, file_name, content_type, size_bytes, storage_key, checksum, created_at, completed_at from attachments
where post_id = $1
  and completed_at is not null
order by created_at asc, id asc
`

func (q *Queries) ListAttachmentsByPostID(ctx context.Context, postID *uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UploaderID,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.Checksum,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReapableAttachments = `-- name: ListReapableAttachments :many
select a.id, a.post_id, a.uploader_id, a.file_name, a.content_type, a.size_bytes, a.storage_key, a.checksum, a.created_at, a.completed_at
from attachments a
left join posts p on p.id = a.post_id
where (a.post_id is null and a.created_at < $1)
   or (p.deleted_at is not null)
`

func (q *Queries) ListReapableAttachments(ctx context.Context, olderThan time.Time) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listReapableAttachments, olderThan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UploaderID,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.Checksum,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbindByPostID = `-- name: UnbindByPostID :exec
update attachments
set post_id = null
where post_id = $1
`

func (q *Queries) UnbindByPostID(ctx context.Context, postID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, unbindByPostID, postID)
	return err
}
