// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emojis.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteReaction = `-- name: DeleteReaction :exec
delete from reactions
where post_id = $1
  and emoji_id = $2
  and user_id = $3
`

type DeleteReactionParams struct {
	PostID  uuid.UUID
	EmojiID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeleteReaction(ctx context.Context, arg DeleteReactionParams) error {
	_, err := q.db.Exec(ctx, deleteReaction, arg.PostID, arg.EmojiID, arg.UserID)
	return err
}

const getEmojiByID = `-- name: GetEmojiByID :one
select id, shortcode, storage_key, checksum, created_at
from emojis
where id = $1
`

func (q *Queries) GetEmojiByID(ctx context.Context, id uuid.UUID) (Emoji, error) {
	row := q.db.QueryRow(ctx, getEmojiByID, id)
	var i Emoji
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.StorageKey,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const getEmojiByShortcode = `-- name: GetEmojiByShortcode :one
select id, shortcode, storage_key, checksum, created_at
from emojis
where shortcode = $1
`

func (q *Queries) GetEmojiByShortcode(ctx context.Context, shortcode string) (Emoji, error) {
	row := q.db.QueryRow(ctx, getEmojiByShortcode, shortcode)
	var i Emoji
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.StorageKey,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const insertEmoji = `-- name: InsertEmoji :one
insert into emojis (shortcode, storage_key, checksum)
values ($1, $2, $3)
returning id, shortcode, storage_key, checksum, created_at
`

type InsertEmojiParams struct {
	Shortcode  string
	StorageKey string
	Checksum   string
}

func (q *Queries) InsertEmoji(ctx context.Context, arg InsertEmojiParams) (Emoji, error) {
	row := q.db.QueryRow(ctx, insertEmoji, arg.Shortcode, arg.StorageKey, arg.Checksum)
	var i Emoji
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.StorageKey,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const insertReaction = `-- name: InsertReaction :exec
insert into reactions (post_id, emoji_id, user_id)
values ($1, $2, $3)
on conflict (post_id, emoji_id, user_id) do nothing
`

type InsertReactionParams struct {
	PostID  uuid.UUID
	EmojiID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) InsertReaction(ctx context.Context, arg InsertReactionParams) error {
	_, err := q.db.Exec(ctx, insertReaction, arg.PostID, arg.EmojiID, arg.UserID)
	return err
}

const listEmojis = `-- name: ListEmojis :many
select id, shortcode, storage_key, checksum, created_at
from emojis
order by shortcode asc
`

func (q *Queries) ListEmojis(ctx context.Context) ([]Emoji, error) {
	rows, err := q.db.Query(ctx, listEmojis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Emoji
	for rows.Next() {
		var i Emoji
		if err := rows.Scan(
			&i.ID,
			&i.Shortcode,
			&i.StorageKey,
			&i.Checksum,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionRowsForPosts = `-- name: ListReactionRowsForPosts :many
select
    r.post_id,
    e.id as emoji_id,
    e.shortcode,
    e.storage_key,
    e.checksum,
    e.created_at as emoji_created_at,
    r.user_id,
    r.created_at as reacted_at
from reactions r
join emojis e on e.id = r.emoji_id
where r.post_id = any($1::uuid[])
order by r.post_id, r.created_at, e.id, r.user_id
`

type ListReactionRowsForPostsRow struct {
	PostID         uuid.UUID
	EmojiID        uuid.UUID
	Shortcode      string
	StorageKey     string
	Checksum       string
	EmojiCreatedAt time.Time
	UserID         uuid.UUID
	ReactedAt      time.Time
}

func (q *Queries) ListReactionRowsForPosts(ctx context.Context, postIds []uuid.UUID) ([]ListReactionRowsForPostsRow, error) {
	rows, err := q.db.Query(ctx, listReactionRowsForPosts, postIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReactionRowsForPostsRow
	for rows.Next() {
		var i ListReactionRowsForPostsRow
		if err := rows.Scan(
			&i.PostID,
			&i.EmojiID,
			&i.Shortcode,
			&i.StorageKey,
			&i.Checksum,
			&i.EmojiCreatedAt,
			&i.UserID,
			&i.ReactedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmoji = `-- name: UpdateEmoji :one
update emojis
set storage_key = $1,
    checksum = $2
where shortcode = $3
returning id, shortcode, storage_key, checksum, created_at
`

type UpdateEmojiParams struct {
	StorageKey string
	Checksum   string
	Shortcode  string
}

func (q *Queries) UpdateEmoji(ctx context.Context, arg UpdateEmojiParams) (Emoji, error) {
	row := q.db.QueryRow(ctx, updateEmoji, arg.StorageKey, arg.Checksum, arg.Shortcode)
	var i Emoji
	err := row.Scan(
		&i.ID,
		&i.Shortcode,
		&i.StorageKey,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}
