// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"
)

const latestChangeEventID = `-- name: LatestChangeEventID :one
select coalesce(max(id), 0)::bigint
from change_events
`

func (q *Queries) LatestChangeEventID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, latestChangeEventID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listChangeEventsAfter = `-- name: ListChangeEventsAfter :many
select id, event_type, channel_id, post_id, thread_root_id, created_at
from change_events
where id > $1::bigint
order by id asc
limit $2
`

type ListChangeEventsAfterParams struct {
	AfterID  int64
	RowLimit int32
}

func (q *Queries) ListChangeEventsAfter(ctx context.Context, arg ListChangeEventsAfterParams) ([]ChangeEvent, error) {
	rows, err := q.db.Query(ctx, listChangeEventsAfter, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangeEvent
	for rows.Next() {
		var i ChangeEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ChannelID,
			&i.PostID,
			&i.ThreadRootID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
