// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID                uuid.UUID
	PostID            *uuid.UUID
	UploaderID        uuid.UUID
	FileName          string
	ContentType       string
	SizeBytes         int64
	StorageKey        string
	Checksum          string
	CreatedAt         time.Time
	CompletedAt       *time.Time
	DeletionPendingAt *time.Time
	DeletionAttempts  int32
	DeletionError     pgtype.Text
}

type ChangeEvent struct {
	ID           int64
	EventType    string
	ChannelID    *uuid.UUID
	PostID       *uuid.UUID
	ThreadRootID *uuid.UUID
	CreatedAt    time.Time
}

type Channel struct {
	ID        uuid.UUID
	ParentID  *uuid.UUID
	Name      string
	SortKey   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Emoji struct {
	ID         uuid.UUID
	Shortcode  string
	StorageKey string
	Checksum   string
	CreatedAt  time.Time
}

type Post struct {
	ID           uuid.UUID
	ChannelID    uuid.UUID
	ThreadRootID *uuid.UUID
	AuthorID     uuid.UUID
	Body         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	EditedAt     *time.Time
	DeletedAt    *time.Time
}

type Reaction struct {
	PostID    uuid.UUID
	EmojiID   uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

type User struct {
	ID         uuid.UUID
	CognitoSub string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
