// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countReplies = `-- name: CountReplies :one
select count(*)::bigint
from posts
where thread_root_id = $1::uuid
  and deleted_at is null
`

func (q *Queries) CountReplies(ctx context.Context, threadRootID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReplies, threadRootID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPost = `-- name: GetPost :one
select id, channel_id, thread_root_id, author_id, body, created_at, updated_at, edited_at, deleted_at
from posts
where id = $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertPost = `-- name: InsertPost :one
insert into posts (channel_id, thread_root_id, author_id, body)
values ($1, $2, $3, $4)
returning id, channel_id, thread_root_id, author_id, body, created_at, updated_at, edited_at, deleted_at
`

type InsertPostParams struct {
	ChannelID    uuid.UUID
	ThreadRootID *uuid.UUID
	AuthorID     uuid.UUID
	Body         string
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, insertPost,
		arg.ChannelID,
		arg.ThreadRootID,
		arg.AuthorID,
		arg.Body,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const lastReplyAt = `-- name: LastReplyAt :one
select created_at
from posts
where thread_root_id = $1::uuid
  and deleted_at is null
order by created_at desc, id desc
limit 1
`

func (q *Queries) LastReplyAt(ctx context.Context, threadRootID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastReplyAt, threadRootID)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const listThreadReplies = `-- name: ListThreadReplies :many
select
    p.id,
    p.channel_id,
    p.thread_root_id,
    p.author_id,
    p.body,
    p.created_at,
    p.updated_at,
    p.edited_at,
    p.deleted_at,
    0::bigint as reply_count,
    null::timestamptz as last_reply_at
from posts p
where p.thread_root_id = $1::uuid
  and p.deleted_at is null
order by p.created_at asc, p.id asc
`

type ListThreadRepliesRow struct {
	ID           uuid.UUID
	ChannelID    uuid.UUID
	ThreadRootID *uuid.UUID
	AuthorID     uuid.UUID
	Body         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	EditedAt     *time.Time
	DeletedAt    *time.Time
	ReplyCount   int64
	LastReplyAt  *time.Time
}

func (q *Queries) ListThreadReplies(ctx context.Context, threadRootID uuid.UUID) ([]ListThreadRepliesRow, error) {
	rows, err := q.db.Query(ctx, listThreadReplies, threadRootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadRepliesRow
	for rows.Next() {
		var i ListThreadRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ThreadRootID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.ReplyCount,
			&i.LastReplyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineAround = `-- name: ListTimelineAround :many
select
    p.id,
    p.channel_id,
    p.thread_root_id,
    p.author_id,
    p.body,
    p.created_at,
    p.updated_at,
    p.edited_at,
    p.deleted_at,
    coalesce(s.reply_count, 0)::bigint as reply_count,
    s.last_reply_at
from posts target
join posts p on p.channel_id = target.channel_id
left join (
    select thread_root_id,
           count(*)::bigint as reply_count,
           max(created_at) as last_reply_at
    from posts
    where deleted_at is null
      and thread_root_id is not null
    group by thread_root_id
) s on s.thread_root_id = p.id
where target.id = $1::uuid
  and target.channel_id = $2::uuid
  and target.thread_root_id is null
  and target.deleted_at is null
  and p.thread_root_id is null
  and p.deleted_at is null
  and (
    p.created_at < target.created_at
    or (p.created_at = target.created_at and p.id <= target.id)
  )
order by p.created_at desc, p.id desc
limit $3
`

type ListTimelineAroundParams struct {
	AroundID  uuid.UUID
	ChannelID uuid.UUID
	RowLimit  int32
}

type ListTimelineAroundRow struct {
	ID           uuid.UUID
	ChannelID    uuid.UUID
	ThreadRootID *uuid.UUID
	AuthorID     uuid.UUID
	Body         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	EditedAt     *time.Time
	DeletedAt    *time.Time
	ReplyCount   int64
	LastReplyAt  interface{}
}

func (q *Queries) ListTimelineAround(ctx context.Context, arg ListTimelineAroundParams) ([]ListTimelineAroundRow, error) {
	rows, err := q.db.Query(ctx, listTimelineAround, arg.AroundID, arg.ChannelID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelineAroundRow
	for rows.Next() {
		var i ListTimelineAroundRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ThreadRootID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.ReplyCount,
			&i.LastReplyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineBefore = `-- name: ListTimelineBefore :many
select
    p.id,
    p.channel_id,
    p.thread_root_id,
    p.author_id,
    p.body,
    p.created_at,
    p.updated_at,
    p.edited_at,
    p.deleted_at,
    coalesce(s.reply_count, 0)::bigint as reply_count,
    s.last_reply_at
from posts p
left join (
    select thread_root_id,
           count(*)::bigint as reply_count,
           max(created_at) as last_reply_at
    from posts
    where deleted_at is null
      and thread_root_id is not null
    group by thread_root_id
) s on s.thread_root_id = p.id
where p.channel_id = $1
  and p.thread_root_id is null
  and p.deleted_at is null
  and (
    p.created_at < $2::timestamptz
    or (
      p.created_at = $2::timestamptz
      and p.id < $3::uuid
    )
  )
order by p.created_at desc, p.id desc
limit $4
`

type ListTimelineBeforeParams struct {
	ChannelID       uuid.UUID
	BeforeCreatedAt time.Time
	BeforeID        uuid.UUID
	RowLimit        int32
}

type ListTimelineBeforeRow struct {
	ID           uuid.UUID
	ChannelID    uuid.UUID
	ThreadRootID *uuid.UUID
	AuthorID     uuid.UUID
	Body         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	EditedAt     *time.Time
	DeletedAt    *time.Time
	ReplyCount   int64
	LastReplyAt  interface{}
}

func (q *Queries) ListTimelineBefore(ctx context.Context, arg ListTimelineBeforeParams) ([]ListTimelineBeforeRow, error) {
	rows, err := q.db.Query(ctx, listTimelineBefore,
		arg.ChannelID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelineBeforeRow
	for rows.Next() {
		var i ListTimelineBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ThreadRootID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.ReplyCount,
			&i.LastReplyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineLatest = `-- name: ListTimelineLatest :many
select
    p.id,
    p.channel_id,
    p.thread_root_id,
    p.author_id,
    p.body,
    p.created_at,
    p.updated_at,
    p.edited_at,
    p.deleted_at,
    coalesce(s.reply_count, 0)::bigint as reply_count,
    s.last_reply_at
from posts p
left join (
    select thread_root_id,
           count(*)::bigint as reply_count,
           max(created_at) as last_reply_at
    from posts
    where deleted_at is null
      and thread_root_id is not null
    group by thread_root_id
) s on s.thread_root_id = p.id
where p.channel_id = $1
  and p.thread_root_id is null
  and p.deleted_at is null
order by p.created_at desc, p.id desc
limit $2
`

type ListTimelineLatestParams struct {
	ChannelID uuid.UUID
	RowLimit  int32
}

type ListTimelineLatestRow struct {
	ID           uuid.UUID
	ChannelID    uuid.UUID
	ThreadRootID *uuid.UUID
	AuthorID     uuid.UUID
	Body         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	EditedAt     *time.Time
	DeletedAt    *time.Time
	ReplyCount   int64
	LastReplyAt  interface{}
}

func (q *Queries) ListTimelineLatest(ctx context.Context, arg ListTimelineLatestParams) ([]ListTimelineLatestRow, error) {
	rows, err := q.db.Query(ctx, listTimelineLatest, arg.ChannelID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelineLatestRow
	for rows.Next() {
		var i ListTimelineLatestRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ThreadRootID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.ReplyCount,
			&i.LastReplyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePost = `-- name: SoftDeletePost :one
update posts
set deleted_at = now(),
    updated_at = now()
where id = $1
  and deleted_at is null
returning id, channel_id, thread_root_id, author_id, body, created_at, updated_at, edited_at, deleted_at
`

func (q *Queries) SoftDeletePost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, softDeletePost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePostBody = `-- name: UpdatePostBody :one
update posts
set body = $1,
    edited_at = now(),
    updated_at = now()
where id = $2
  and deleted_at is null
returning id, channel_id, thread_root_id, author_id, body, created_at, updated_at, edited_at, deleted_at
`

type UpdatePostBodyParams struct {
	Body string
	ID   uuid.UUID
}

func (q *Queries) UpdatePostBody(ctx context.Context, arg UpdatePostBodyParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePostBody, arg.Body, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}
