// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteChannel = `-- name: DeleteChannel :exec
delete from channels
where id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const getChannel = `-- name: GetChannel :one
select id, parent_id, name, sort_key, created_at, updated_at
from channels
where id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.SortKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAuthSubject = `-- name: GetUserByAuthSubject :one
select id, auth_subject, created_at, updated_at
from users
where auth_subject = $1
`

func (q *Queries) GetUserByAuthSubject(ctx context.Context, authSubject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuthSubject, authSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, auth_subject, created_at, updated_at
from users
where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChannel = `-- name: InsertChannel :one
insert into channels (parent_id, name, sort_key)
values ($1, $2, $3)
returning id, parent_id, name, sort_key, created_at, updated_at
`

type InsertChannelParams struct {
	ParentID *uuid.UUID
	Name     string
	SortKey  string
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, insertChannel, arg.ParentID, arg.Name, arg.SortKey)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.SortKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserByAuthSubject = `-- name: InsertUserByAuthSubject :one
insert into users (auth_subject)
values ($1)
returning id, auth_subject, created_at, updated_at
`

func (q *Queries) InsertUserByAuthSubject(ctx context.Context, authSubject string) (User, error) {
	row := q.db.QueryRow(ctx, insertUserByAuthSubject, authSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
select id, parent_id, name, sort_key, created_at, updated_at
from channels
order by parent_id nulls first, sort_key, id
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.SortKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiblings = `-- name: ListSiblings :many
select id, parent_id, name, sort_key, created_at, updated_at
from channels
where parent_id is not distinct from $1
order by sort_key, id
`

func (q *Queries) ListSiblings(ctx context.Context, parentID *uuid.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listSiblings, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.SortKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameChannel = `-- name: RenameChannel :one
update channels
set name = $1, updated_at = now()
where id = $2
returning id, parent_id, name, sort_key, created_at, updated_at
`

type RenameChannelParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) RenameChannel(ctx context.Context, arg RenameChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, renameChannel, arg.Name, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.SortKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChannelLocation = `-- name: UpdateChannelLocation :one
update channels
set parent_id = $1,
    sort_key = $2,
    updated_at = now()
where id = $3
returning id, parent_id, name, sort_key, created_at, updated_at
`

type UpdateChannelLocationParams struct {
	ParentID *uuid.UUID
	SortKey  string
	ID       uuid.UUID
}

func (q *Queries) UpdateChannelLocation(ctx context.Context, arg UpdateChannelLocationParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannelLocation, arg.ParentID, arg.SortKey, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.SortKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
