// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const searchPostsBefore = `-- name: SearchPostsBefore :many
select
    p.id as post_id,
    coalesce(p.thread_root_id, p.id)::uuid as timeline_post_id,
    p.channel_id,
    c.name as channel_name,
    p.thread_root_id,
    p.body,
    p.created_at
from posts p
join channels c on c.id = p.channel_id
where p.deleted_at is null
  and lower(p.body) like likequery(lower($1))
  and ($2::uuid is null or p.channel_id = $2::uuid)
  and ($3::timestamptz is null or p.created_at >= $3::timestamptz)
  and ($4::timestamptz is null or p.created_at <= $4::timestamptz)
  and (
    p.created_at < $5::timestamptz
    or (
      p.created_at = $5::timestamptz
      and p.id < $6::uuid
    )
  )
order by p.created_at desc, p.id desc
limit $7
`

type SearchPostsBeforeParams struct {
	SearchQuery     string
	ChannelID       *uuid.UUID
	CreatedFrom     *time.Time
	CreatedTo       *time.Time
	BeforeCreatedAt time.Time
	BeforeID        uuid.UUID
	RowLimit        int32
}

type SearchPostsBeforeRow struct {
	PostID         uuid.UUID
	TimelinePostID uuid.UUID
	ChannelID      uuid.UUID
	ChannelName    string
	ThreadRootID   *uuid.UUID
	Body           string
	CreatedAt      time.Time
}

func (q *Queries) SearchPostsBefore(ctx context.Context, arg SearchPostsBeforeParams) ([]SearchPostsBeforeRow, error) {
	rows, err := q.db.Query(ctx, searchPostsBefore,
		arg.SearchQuery,
		arg.ChannelID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsBeforeRow
	for rows.Next() {
		var i SearchPostsBeforeRow
		if err := rows.Scan(
			&i.PostID,
			&i.TimelinePostID,
			&i.ChannelID,
			&i.ChannelName,
			&i.ThreadRootID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsLatest = `-- name: SearchPostsLatest :many
select
    p.id as post_id,
    coalesce(p.thread_root_id, p.id)::uuid as timeline_post_id,
    p.channel_id,
    c.name as channel_name,
    p.thread_root_id,
    p.body,
    p.created_at
from posts p
join channels c on c.id = p.channel_id
where p.deleted_at is null
  and lower(p.body) like likequery(lower($1))
  and ($2::uuid is null or p.channel_id = $2::uuid)
  and ($3::timestamptz is null or p.created_at >= $3::timestamptz)
  and ($4::timestamptz is null or p.created_at <= $4::timestamptz)
order by p.created_at desc, p.id desc
limit $5
`

type SearchPostsLatestParams struct {
	SearchQuery string
	ChannelID   *uuid.UUID
	CreatedFrom *time.Time
	CreatedTo   *time.Time
	RowLimit    int32
}

type SearchPostsLatestRow struct {
	PostID         uuid.UUID
	TimelinePostID uuid.UUID
	ChannelID      uuid.UUID
	ChannelName    string
	ThreadRootID   *uuid.UUID
	Body           string
	CreatedAt      time.Time
}

func (q *Queries) SearchPostsLatest(ctx context.Context, arg SearchPostsLatestParams) ([]SearchPostsLatestRow, error) {
	rows, err := q.db.Query(ctx, searchPostsLatest,
		arg.SearchQuery,
		arg.ChannelID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsLatestRow
	for rows.Next() {
		var i SearchPostsLatestRow
		if err := rows.Scan(
			&i.PostID,
			&i.TimelinePostID,
			&i.ChannelID,
			&i.ChannelName,
			&i.ThreadRootID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
