/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** チャネル階層を一覧する */
        get: operations["listChannels"];
        put?: never;
        /** チャネルを作成する */
        post: operations["createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** ポストを持たないチャネルを削除する */
        delete: operations["deleteChannel"];
        options?: never;
        head?: never;
        /** チャネルをリネームする */
        patch: operations["renameChannel"];
        trace?: never;
    };
    "/v1/channels/{channelId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 親の付け替えと並び替え */
        post: operations["moveChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels/{channelId}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        /**
         * チャネル直下のポストを keyset で取得する
         * @description thread_root_id が null の行のみを返す。
         *     カーソル無しなら最新 limit 件（既定 10）を昇順で返す。
         *     before を付けると、そのカーソルより古いポストを昇順で返す。
         */
        get: operations["listChannelPosts"];
        put?: never;
        /** チャネル直下にポストを作成する */
        post: operations["createChannelPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** ポストを論理削除する */
        delete: operations["deletePost"];
        options?: never;
        head?: never;
        /** ポスト本文を上書きする */
        patch: operations["editPost"];
        trace?: never;
    };
    "/v1/posts/{postId}/thread": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        /**
         * 親ポストと返信を古い順で取得する
         * @description 親が論理削除済みならプレースホルダとして deleted=true で返す。
         *     削除済みの返信は含めない。
         */
        get: operations["getThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/posts/{postId}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * スレッドへ返信する
         * @description 親が返信でも thread_root_id を継承し、多段スレッドは作らない。
         */
        post: operations["createReply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attachments/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添付のアップロード用署名付き URL を発行する */
        post: operations["startAttachmentUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attachments/{attachmentId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** アップロード完了を通知しメタデータを確定する */
        post: operations["completeAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attachments/{attachmentId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        /** ダウンロード用の短期署名付き URL を発行する */
        get: operations["getAttachmentDownload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/emojis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 登録済みのカスタム絵文字を一覧する */
        get: operations["listEmojis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/emojis/{shortcode}/image": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shortcode: components["parameters"]["EmojiShortcode"];
            };
            cookie?: never;
        };
        /** カスタム絵文字の PNG を取得する */
        get: operations["getEmojiImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/posts/{postId}/reactions/{emojiId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
                emojiId: components["parameters"]["EmojiId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * ポストへリアクションを付与する
         * @description 同じ付与要求が重複しても既存状態を維持して成功する。
         */
        put: operations["addReaction"];
        post?: never;
        /** 自身のリアクションを解除する */
        delete: operations["removeReaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ポスト本文を全文検索する */
        get: operations["searchPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 指定したイベント ID より後の変更を取得する */
        get: operations["listChangeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "unhealthy";
            /** @enum {string} */
            database: "ok" | "skipped" | "unreachable";
        };
        Error: {
            /** @description 機械可読なエラーコード */
            code: string;
            /** @description 人間可読なメッセージ */
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Channel: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId?: string | null;
            name: string;
            sortKey: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ChannelList: {
            channels: components["schemas"]["Channel"][];
        };
        CreateChannelRequest: {
            name: string;
            /** Format: uuid */
            parentId?: string | null;
        };
        RenameChannelRequest: {
            name: string;
        };
        MoveChannelRequest: {
            /** Format: uuid */
            parentId?: string | null;
            /**
             * Format: uuid
             * @description このチャネルの直前に挿入する。null なら末尾。
             */
            beforeId?: string | null;
            /**
             * Format: uuid
             * @description このチャネルの直後に挿入する。
             */
            afterId?: string | null;
        };
        Post: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            channelId: string;
            /** Format: uuid */
            threadRootId?: string | null;
            /** Format: uuid */
            authorId: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            editedAt?: string | null;
            /** @description 論理削除済み。スレッド親のプレースホルダでのみ true になる。 */
            deleted: boolean;
            replyCount: number;
            /** Format: date-time */
            lastReplyAt?: string | null;
            attachments?: components["schemas"]["Attachment"][];
            /** @description 最初に付与された順のリアクション集計。 */
            reactions?: components["schemas"]["Reaction"][];
        };
        PostList: {
            posts: components["schemas"]["Post"][];
            /** @description より古いポストを取得するカーソル。これ以上過去が無ければ null。 */
            nextBefore?: string | null;
        };
        CreatePostRequest: {
            /** @description 本文。添付が無い場合は空であってはならない。 */
            body?: string;
            attachmentIds?: string[];
        };
        EditPostRequest: {
            body: string;
            /** @description 指定した場合は添付の集合を置き換える。省略時は既存の添付を維持する。 */
            attachmentIds?: string[];
        };
        Attachment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            postId?: string | null;
            fileName: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
            checksum: string;
            /** Format: date-time */
            createdAt: string;
        };
        StartUploadRequest: {
            fileName: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
            /** @description SHA-256 の hex */
            checksum: string;
        };
        StartUploadResponse: {
            /** Format: uuid */
            id: string;
            uploadUrl: string;
            headers: {
                [key: string]: string;
            };
        };
        DownloadUrlResponse: {
            url: string;
            /** Format: date-time */
            expiresAt: string;
        };
        Emoji: {
            /** Format: uuid */
            id: string;
            shortcode: string;
            imagePath: string;
            checksum: string;
        };
        EmojiList: {
            emojis: components["schemas"]["Emoji"][];
        };
        Reaction: {
            emoji: components["schemas"]["Emoji"];
            count: number;
            reactedByMe: boolean;
            /** @description 付与者 ID。reactedByMe が true の場合は現在のユーザーを先頭にする。 */
            reactorIds: string[];
        };
        Thread: {
            root: components["schemas"]["Post"];
            replies: components["schemas"]["Post"][];
        };
        SearchResult: {
            /** Format: uuid */
            postId: string;
            /**
             * Format: uuid
             * @description チャネルタイムラインに表示するルートポスト ID。
             */
            timelinePostId: string;
            /** Format: uuid */
            channelId: string;
            channelName: string;
            /** Format: uuid */
            threadRootId?: string | null;
            body: string;
            /** Format: date-time */
            createdAt: string;
        };
        SearchResultPage: {
            results: components["schemas"]["SearchResult"][];
            nextCursor?: string | null;
        };
        ChangeEvent: {
            /** @description JavaScript で精度を失わない十進文字列の単調増加 ID。 */
            id: string;
            /** @enum {string} */
            eventType: "channel.created" | "channel.updated" | "channel.deleted" | "post.created" | "post.updated" | "post.deleted" | "reply.created" | "reply.updated" | "reply.deleted" | "reaction.updated";
            /** Format: uuid */
            channelId?: string | null;
            /** Format: uuid */
            postId?: string | null;
            /** Format: uuid */
            threadRootId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ChangeEventPage: {
            events: components["schemas"]["ChangeEvent"][];
            nextAfter: string;
            hasMore: boolean;
        };
    };
    responses: {
        /** @description 一貫したエラー形式 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ChannelId: string;
        PostId: string;
        AttachmentId: string;
        EmojiId: string;
        EmojiShortcode: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 稼働中 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 依存先が落ちている */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 階層関係と並び順を復元できるチャネル一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChannelRequest"];
            };
        };
        responses: {
            /** @description 作成されたチャネル */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    renameChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameChannelRequest"];
            };
        };
        responses: {
            /** @description 更新後のチャネル */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    moveChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveChannelRequest"];
            };
        };
        responses: {
            /** @description 適用後の親と sort_key を含むチャネル */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChannelPosts: {
        parameters: {
            query?: {
                limit?: number;
                /** @description より古いポストを取るカーソル（nextBefore の値） */
                before?: string;
                /** @description 検索結果から移動するとき、このルートポストを含む履歴を返す。 */
                around?: string;
            };
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 昇順のポスト一覧と、さらに過去がある場合のカーソル */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createChannelPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description 作成されたポスト */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deletePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    editPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditPostRequest"];
            };
        };
        responses: {
            /** @description 更新後のポスト */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スレッド */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createReply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description 作成された返信 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startAttachmentUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartUploadRequest"];
            };
        };
        responses: {
            /** @description アップロード開始 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartUploadResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    completeAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 確定した添付 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAttachmentDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 署名付き URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrlResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listEmojis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ショートコード順の絵文字カタログ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmojiList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getEmojiImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shortcode: components["parameters"]["EmojiShortcode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 絵文字画像 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    addReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
                emojiId: components["parameters"]["EmojiId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 付与後のリアクション集計 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reaction"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    removeReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
                emojiId: components["parameters"]["EmojiId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 解除成功。既に解除済みの場合も成功する。 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    searchPosts: {
        parameters: {
            query: {
                q: string;
                channelId?: string;
                createdFrom?: string;
                createdTo?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 新しい順の検索結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChangeEvents: {
        parameters: {
            query?: {
                after?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ID の昇順に並んだ変更イベント */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeEventPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
